### ISSUE TITLE
Generar índice de grado de escasez

### ISSUE THREAD

**Issue by aleestrada** [sostenibilidad-unam/SHV#100]
Generar un índice que refleje la escasez de agua en de cada una de las AGEB's.

# Carpeta en la que se encuentran los datos
\SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez

# Insumos Iniciales

Los insumos para el modelo se encuentran en la carpeta:
\SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\insumos

A continuación se listan los insumos, así como su ruta de origen:
 
- Población por AGEB en el 2017:  Número total de habitantes por AGEB, para su cálculo se utilizó como base la población por AGEB en 2010 y para las proyecciones al 2017 se utilizaron las proyecciones de tasas de crecimiento por localidad de CONAPO. Fuente: Censo de población y vivienda 2010.
\CARPETAS_TRABAJO\aestrada\megadapt\censos_ei\poblacion_ageb

- Número de viviendas por AGEB: Número total de viviendas particulares habitadas por AGEB. 
Fuente: Censo de población y vivienda 2010
\CARPETAS_TRABAJO\aestrada\megadapt\censos_ei\censo_df_2010

- Número cisternas por AGEB: Número total de cisternas por AGEB, con información de la Encuesta Intercensal del 2015. Fuente: Encuesta intercensal 2015.
\CARPETAS_TRABAJO\igrave\MEGADAPT\escasez\producto\cisternas_viv

- Ingreso: Ingreso total por delegación
 Encuesta intercensal 2015, \CARPETAS_TRABAJO\aestrada\megadapt\censos_ei

- Zonas críticas por delegación: Proporción de la AGEB cuyas viviendas tienen menos de 4 horas de agua al día. Fuente: SACMEX
\mega_procesamiento\banco_datos\tandeo\tandeo_agebs

- Presión hidráulica. Presión hidráulica en función de la altura a nivel medio del mar y la entrada al Cutzamala. Fuente: https://github.com/sostenibilidad-unam/SHV/issues/122
/sig_megadapt/procesamiento/presion_hidraulica

- Viviendas sin conexión a la red. Proporción de viviendas por AGEB que no están conectadas a la red de agua potable.
\SIG\desarrollo\sig_megadapt\finales\falta_dist

- Antigüedad de la infraestructura. Antigüedad del crecimiento de la mancha urbana
\SIG\desarrollo\sig_megadapt\finales\antiguedad

# Insumos Finales

Insumo|Archivo|Variable|Ruta
-- | -- | -- | --
Densidad de población | den_pob_17_ageb.shp | Densidad de población por km^2 para el año 2017 | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\producto
Zonas críticas | agebs_tandeo.shp | Proporción de la AGEB cuyas viviendas tienen menos de 4 horas de agua al día | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\insumos\zonas_crit
Cisternas | cisternas_viv.shp | Número de cisternas por AGEB | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\producto
Ingreso | income_pc.shp | Ingreso per cápita por delegación | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\producto
Días sin agua | tp_dsa_agebs_cdmx_v3.shp | Número promedio de días sin agua por AGEB, de acuerdo a los reportes | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\insumos\dias_sagua
Antiguedad | antiguedad.shp | Edad de la infraestructura | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\insumos\antiguedad
Falta en la distribución | falta_dist.shp | Proporción de viviendas sin conexión a la red de agua | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\insumos\viviendas_sagua
Presión hidráulica | presion_hidraulica.shp | Índice de presión hidráulica (sin pozos) | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\insumos\presion_hid

# Producto
Generar un índice que refleje la escasez de agua en cada una de las AGEB's.
SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\producto\indice_escasez_max_comp.Rmd
La capa resultante es: 
SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\producto\escasez_ant_pres.shp

# Proceso
- [x] Revisar la estructura de la función de grado de protesta @aleestrada 
- [x] Obtener mapa del tiempo de atención de reportes de faltas de agua @AlfMedina 
- [x] Generar índice de grado de escasez. @iaga y @aleestrada

**Comment by AlfMedina** [comment]
Usando el código para asignar col_id se adapta para procesar la base "FUGAS_FALTAS Y EFICIENCIA ANIOS 2017 Y 2018.xlsx" a colonias (sólo para el 2017). Se cortó en el coeficiente de similitud de 0.65 (sin una revisión extensiva).

El código quita los reportes repetidos (misma fecha y misma calle) y escribe una capa con el promedio de cada colonia que hay en la base y se hizo el siguiente mapa:

![media_dias_sin_agua_v2](https://user-images.githubusercontent.com/22686851/51276996-ed196300-199b-11e9-88a6-1666686cda6f.png)

El script `faltas_dias_2017.Rmd` se encuentra en:
\CARPETAS_TRABAJO\amedina\MEGADAPT

**Comment by JosueMA** [comment]
Con el fin de generar insumos para las funciones de valor, se calcularon las siguientes variables:

*  Cisternas por cada vivienda (`cisternas_viv`).
*  Ingreso per cápita (`ingreso_per`).
*  Viviendas por cada m^2 (`viviendas_ageb_area`).

Además, se localizaron y eliminaron los datos no especificados en la encuesta intercensal en el rubro de ingreso (`INGTRMEN` = 999999).

Posteriormente se calcularon mínimos y máximos de las variables calculadas.

Trabajo realizado por @AlfMedina y @JosueMA. Productos en la ruta: "/SIG/desarrollo/sig_megadapt/procesamiento/fn_grado_protesta/economico/ind_imp_ec_v2.Rmd".

**Comment by aleestrada** [comment]
# Propuesta 2. Funciones de valor (versión final)

Por recomendación de Luis, se realizó el índice utilizando funciones de valor, en este sentido, se utilizaron las siguientes variables a las cuales se les asignó una función de valor:

- Densidad de población por AGEB: población por ageb / km^2
- Zonas críticas: Proporción de la AGEB con menos de 4 horas de agua al día.
- Número de cisternas: Proporción de cisternas por vivienda a nivel delegación.
- Ingreso: Ingreso *per cápita* por delegación.
- Días sin agua: Número promedio de días sin agua por delegación de acuerdo a los reportes de personas.
- Viviendas sin agua: Proporción de viviendas por AGEB sin conexión a la red de agua.
- Antigüedad: Edad de la infraestructura.
- Presión hidráulica: Presión hidráulica de la tubería de abasto de agua.

## Funciones utilizadas

#### Densidad de población por AGEB: población por ageb / km^2 
- Logística invertida.
- a = 0.3
- Centro = 15,000

![image](https://user-images.githubusercontent.com/25159102/52804498-fc96d500-3049-11e9-95fb-fa863bfd54c5.png)


#### Zonas críticas: Proporción de la AGEB con menos de 4 horas de agua al día.
- Campana
- a = 23
- Centro = 23
![image](https://user-images.githubusercontent.com/25159102/52509422-ad6e2180-2bbd-11e9-8d4e-03980d4e908b.png)


#### Número de cisternas: Proporción de cisternas por vivienda a nivel delegación.
- Convexa
- Gama = 0.05

![image](https://user-images.githubusercontent.com/25159102/52509428-b52dc600-2bbd-11e9-802e-80e39655cee3.png)



#### Ingreso: Ingreso *per cápita* por delegación.
- Convexa
- Gamma = 0.015
![image](https://user-images.githubusercontent.com/25159102/52509436-bd860100-2bbd-11e9-891f-69a4a9317e81.png)

#### Días sin agua: Número promedio de días sin agua por delegación de acuerdo a los reportes de personas. 
- Campana

![imagen](https://user-images.githubusercontent.com/41757755/54060209-793c4f80-41c1-11e9-948f-8325c9506805.png)

**Comment by aleestrada** [comment]
# Incorporación de la variable antigüedad (edad de la infraestructura) en el índice.

Se consideró incorporar la edad de la infraestructura en el índice, para tal motivo se realizó un mapa con esta variable para conocer su distribución espacial en la ciudad.

A continuación, se presenta este mapa.

![image](https://user-images.githubusercontent.com/25159102/53372154-c4c84100-3917-11e9-8e93-79365d9e17f7.png)

Al realizar la comparación del mapa de antigüedad con los días sin agua, tanto del censo como de los reportes, se puede observar que presentan un comportamiento inverso.

**Comment by iaga** [comment]
Es necesario incluir alguna variable que relacione la acción del SAC al índice de escasez. Las posibles variables a incorporar:

- Presión hidráulica
- Edad de la infraestructura
- Fugas

**Comment by iaga** [comment]
## Mapa 1. Índice de escasez que incluye viviendas sin conexión a la red

![ma_escasez_vivsagua_dsagua](https://user-images.githubusercontent.com/41757755/54311947-4ddbab00-459b-11e9-948e-db6fe55fb555.png)

## Mapa 2. Índice de escasez que incluye viviendas sin conexión a la red y antigüedad

![ma_escasez_vivsagua_dsagua_antig](https://user-images.githubusercontent.com/41757755/54312033-81b6d080-459b-11e9-882f-81e6ae7dba9d.png)

## Mapa 3. Índice de escasez que incluye viviendas sin conexión a la red y fugas

![ma_escasez_vivsagua_dsagua_fugas](https://user-images.githubusercontent.com/41757755/54312052-8bd8cf00-459b-11e9-9045-559d6b72a979.png)

A la fecha (13/03/2019) se decidió utilizar el Mapa 1 (que incluye la variable viviendas sin conexión a la red), ya que la salida con edad de la infraestructura y fugas modifica el patrón espacial de manera considerable. El mapa que incluye la presión hidráulica se generará cuando la capa esté disponible.

**Comment by iaga** [comment]
@serranoycandela la función de valor de viviendas sin conexión a la red se encuentra, por el momento, dentro del script. Es una variable que olvidamos incluir al inicio del índice, pero se agregó al final (está incluida en el mapa de salida).

**Comment by iaga** [comment]
## Mapa del índice de Escasez que incluye a las variables antigüedad de la infraestructura y presión hidráulica

Se incluyeron dos funciones de valor, tomadas del taller de SACMEX de Marzo de 2018:

### Edad de la infraestructura

- Campana invertida
- Centro = 60
- Longitud medida desde el centro = 40

![imagen](https://user-images.githubusercontent.com/41757755/55035714-46c28d00-4fde-11e9-9822-dc89cbaf14fa.png)

### Presión hidráulica

- Logística
- Centro = 0.765
- k = .1815

![imagen](https://user-images.githubusercontent.com/41757755/55036060-20e9b800-4fdf-11e9-828d-4bac01ebdc65.png)

### Producto*

Utilizando la siguiente combinación lineal:

Índice de escasez = ((1/8)*(fv_pob_ageb) + (1/8)*(fv_zonas_crit) + (1/8)*(fv_num_cisternas) + (1/8)*(fv_ingreso) +  (1/8)*(fv_dias_sagua) +  (1/8)*(fv_antiguedad) +  (1/8)*(fv_viviendas_sagua) + (1/8)*(fv_presion_hid))

Se obtuvo el siguiente mapa que refleja el índice de escasez:

![ma_escasez_vivsagua_ant_pres](https://user-images.githubusercontent.com/41757755/55035636-14189480-4fde-11e9-92ea-3d5cd2ab6e7e.png)
 
*Mapa generado con WB= 1.4

### Observaciones:

- Es necesario incluir la cosecha de agua. Se necesitan los datos de Isla Urbana @serranoycandela.

**Comment by aleestrada** [comment]
Se generaran capas en formato JSON para ser utilizadas en la plataforma de value_functions.

**Comment by aleestrada** [comment]
@serranoycandela proporcionó el informe final del estudio realizado por Isla Urbana (IU). Para incorporar al análisis la parte de cosecha de agua, se requieren los datos de captura de agua en un formato que pueda ser manipulable (.csv). 

De igual forma, se deben considerar las limitaciones del estudio realizado por IU, ya que cómo se comenta en el informa los datos estimados no son precisos a nivel manzana y se sugiere su uso sólo a nivel delegación.

**Comment by aleestrada** [comment]
# Índice de escasez con valores máximos para todo el periodo de simulación

En la junta con Luis el 06/05/19 se llegó a la conclusión de que era necesario realizar las funciones de valor considerando los valores máximos posibles a los cuales podría llegar cada una de las variables consideradas en el índice.

Para esto es necesario analizar  aquellas variables cuyo valor máximo se incrementa en tiempo.

Variables cuyo valor máximo no se modificaría a lo largo del tiempo:

- Zonas críticas
- Presión hidráulica
- Viviendas sin conexión a la red de agua

Variables cuyo valor máximo debería modificarse, pero no está considerado en el modelo:

- Promedio de días sin agua
- Ingreso per cápita

Variables cuyo valor máximo debería modificarse:

- Antigüedad
- Proporción de cisternas por vivienda por delegación
- Población por AGEB

## Valores máximos por variable

Variable | Máximo |
--|--|
Num. cisternas | 7948
Antiguedad|108
Población| Se queda el mismo, porque la población no crece, decrece

Máximo. Valor máximo para todo el periodo de simulación (se considera hasta el 2040).

### Número máximo de cisternas por AGEB.

El número de cisternas por AGEB se calcula a partir del número total de viviendas y cisternas a nivel delegación, ver issue https://github.com/sostenibilidad-unam/SHV/issues/132.  Es importante considerar que pueden existir delegaciones con más de una cisterna por vivienda, por lo tanto, se considera que en toda la AGEB pueden existir hasta 2 cisternas por vivienda.

Procedimiento:

1.- Se realizó el cálculo del número total de cisternas posibles por AGEB, dado el escenario máximo en el que existen 2 cisternas por vivienda.
2.- Se obtuvo el valor máximo de cisternas para todas las AGEBS: 7948 cisternas correspondientes a la AGEB 7316.

![imagen](https://user-images.githubusercontent.com/41757755/58915969-f192ae00-86e7-11e9-995a-95b440ebfef2.png)
Se seleccionó una fv convexa creciente con gamma de .16. En verde se observa la zona en que la fv es sensible a los cambios.

### Antigüedad máxima
 
Se consideró la edad máxima inicial (64 años) y se le sumó el intervalo de tiempo comprendido para el periodo de simulación comprendido del año 2016 al 2060. Finalmente, se obtuvo el valor máximo de 108 años para las AGEBS con mayor antigüedad.

![imagen](https://user-images.githubusercontent.com/41757755/58914285-bc845c80-86e3-11e9-96f2-7b64258511e2.png)

Verde. Campana invertida considerado las condiciones iniciales (máx. 60 años) 
Roja. Campana invertida considerado el máximo para todo el tiempo de simulación (máx. 108 años) 
Azul. Logística invertida considerado el máximo para todo el tiempo de simulación (máx. 108 años) 

Con el objetivo de preservar la sensibilidad de la fv a los cambios, se modificó la función a una logística invertida con centro en 40 y longitud medida desde el centro de .14



### Población máxima

Se calcularon las proyecciones de población a nivel AGEB #145, y se obtuvo el máximo del periodo proyectado (2018-2030), el cual es de 595 personas por hectárea, el cual es menor al máximo actual de personas por hectárea: 596. Por lo que la fv no sufre ninguna modificación.

**Comment by edithvilla** [comment]
@aleestrada @iaga 

La coordinadora de MEGADAPT está solicitando que la apoyemos con la siguiente información:

Con qué puntos pueden apoyar?

Mensaje: 
"Estoy escribiendo un articulo sobre los modelos mentales de MEGADAPT. Necesito unos estadísticas de nuestro base de datos, y espero que me pueden ayudar:

1. % de colonias / AGEBS que definimos como “wáter scarce” para propósito de Megadapt (y como definimos escasez de agua)

2. % de AGHEBS expuestas a echarcamientos (o alguna cifra que representa que tanto la ciudad sufre inundaciones)

3. Y luego, para Magdalena Contreras, Xochimilco y Izta, como su situación compara a la ciudad en general (% AGEB Izta  comparado a % AGEB ciudad en general).

4. También me acuerda que hiciste un análisis de las estadísticas socio-económicas de las AGEBs expuestas. Me encantaría revisar estos datos de nuevo. Seria bueno tener esta análisis a la mano de todos modos.

Podemos reunirnos esta semana para este propósito? Estoy copiando Paola y Luis para no hacer lata con la organización de sus tiempos!

Muchas gracias"

**Comment by iaga** [comment]
@edithvilla platicamos con ella y acordamos que nos encargaremos de los puntos relacionados a escasez de agua (1 y 3). 

Por otro lado, para inundaciones necesita la información sobre la afectación constante por encharcamientos e inundaciones i.e. tal vez sea necesario eliminar eventos extremos del análisis.

**Comment by aleestrada** [comment]
@edithvilla  Ya se realizaron los cálculos solicitados, se encuentran en la siguiente ubicación:

\carpetas_trabajo\aestrada\megadapt\estadisticas_escasez.rmd

Se solicitó a Hallie una reunión para revisar los resultados.

Los calculos que se obtuvieron fueron:

Proporción de colonias que reciben menos de 4 hrs diaras de agua por alcaldia y a nivel CDMX.
Proporción de viviendas sin conexión a la red de agua potable por alcaldía y a nivel CDMX.
