### ISSUE TITLE
Crear capa de cisternas por AGEB

### ISSUE THREAD

**Issue by iaga** [sostenibilidad-unam/SHV#132]

**Comment by aleestrada** [comment]
Se generó capa de proporción de cisternas por vivienda por delegación. Los datos se encuentran a nivel AGEB (toda las AGEB's de la delegación tienen la misma proporción).

Se encuentra en:

\SIG\desarrollo\sig_megadapt\entregables\doble_acop_escasez\productos

**Comment by serranoycandela** [comment]
@vichdzgeo

**Comment by iaga** [comment]
## Capa de cisternas por ageb (distinta proporción)

Se obtiene el número de cisternas por AGEB a partir de los datos del censo y la encuesta intercensal. La capa es una APROXIMACIÓN por AGEB debido a que los datos son significativos únicamente a nivel delegación.

Markdown: \CARPETAS_TRABAJO\igrave\MEGADAPT\escasez\producto\capa_cisternas_ageb.Rmd

1.- Proporción de cisternas por DELEGACIÓN
2.- Número de cisternas por AGEB

### Proporción de cisternas por DELEGACIÓN
La proporción de cisternas por delegación se obtuvo a partir del **número total de viviendas por delegación** (cist_del) y el **número de cisternas por delegación** (viv_del):

prop_cisternas_viv_del = cist_del/viv_del

### Número de cisternas por AGEB

El número total de cisternas por AGEB se obtuvo a partir de la  **proporción de cisternas por vivenda por delegación**  (cisternas_viv_del) y el **número total de viviendas por ageb** (viviendas_ageb):

cisternas_viv_ageb = prop_cisternas_viv_del*viviendas_ageb

![ma_cisternas_ageb](https://user-images.githubusercontent.com/41757755/57718165-5192b900-7642-11e9-8756-bcbe55cd4cae.png)

Capa generada: cisternas_viv.shp
