### ISSUE TITLE
Realizar análisis de la base de datos de encharcamientos y realizar índice de inundaciones (datos ii)

### ISSUE THREAD

**Issue by aleestrada** [sostenibilidad-unam/SHV#142]
Analizar las capas proporcionadas por el ii, tanto para inundaciones como para precipitación y generar un índice de inundaciones mediante el análisis de eventos extremos.

**Comment by iaga** [comment]
Se realizó una comparación entre los datos proporcionados por el ii y los del SAC

## Datos del SAC

Encharcamientos|Inundaciones
---|---
![ench_tirante_puntos_criticos_sacmex](https://user-images.githubusercontent.com/41757755/57092329-d12e9880-6cd0-11e9-8af4-b42ea8819f5b.png)|![inud_tirante_puntos_criticos_sacmex](https://user-images.githubusercontent.com/41757755/57092334-d4298900-6cd0-11e9-9795-90cf2e3856cc.png)

## Datos del ii

### Encharcamientos e inundaciones ii (periodo de retorno de 2 años)

Tr_2_cap_0|Tr_2_cap_75|
---|---
![ii_Tr2_cap_0_puntos_criticos_sacmex](https://user-images.githubusercontent.com/41757755/57105305-10b8ad00-6cf0-11e9-91e8-929c628b2a03.png)|![ii_Tr2_cap_75_puntos_criticos_sacmex](https://user-images.githubusercontent.com/41757755/57102555-663d8b80-6ce9-11e9-9c6f-33c00f6b209e.png)

### Encharcamientos e inundaciones ii (periodo de retorno de 500 años)

Tr_500_cap_0|Tr_500_cap_75|
---|---
![ii_Tr500_cap_0_puntos_criticos_sacmex](https://user-images.githubusercontent.com/41757755/57107126-cc7bdb80-6cf4-11e9-9755-fa54fd5f10ee.png)|![ii_Tr500_cap_75_puntos_criticos_sacmex](https://user-images.githubusercontent.com/41757755/57104695-a7846a00-6cee-11e9-97d6-b9abccfa91bd.png)

**Comment by iaga** [comment]
# Índice de inundaciones

De acuerdo con la junta realizada con Luis el 29 de abril del 2019, se acordó que se el modelo de eventos extremos de inundaciones se realizaría mediante un índice, en el que se utilizarían funciones de valor lineales.

Las variables que se considerar en el índice son:

Insumo | Ubicación
--|--
Tirante máximo por AGEB | SIG\desarrollo\sig_megadapt\procesamiento\ii_extre_model\insumos\EstadisticaAGEB
Proporción de ´área con inundación | SIG\desarrollo\sig_megadapt\procesamiento\ii_extre_model\insumos\EstadisticaAGEB

El índice se realizó para los 7 periodos de retorno (Tr) y para los 5 niveles de capacidad de drenaje (Oper) : 
Periodo de retorno
- Tr = 2
- Tr = 5
- Tr = 10
- Tr = 25
- Tr = 50
- Tr = 100
- Tr = 500 

Capacidad de drenaje
- Oper = 0
- Oper = 25
- Oper = 50
- Oper = 75
- Oper = 100

## Normalización

La fórmula para la normalización de los datos (aplicar la función de valor lineal a los datos), se acordó con Luis en la junta del 02 de mayo de 2019 y es la siguiente:

1 + (min(x)/max(x)) - (x_i * (1/max(x)))


## Combinación lineal ponderada. 

alpha_1 * tirante + alpha_2 * prop_area_inund


## Mapas generados

Nota: La combinación lineal ponderada se realizó bajo el caso 1 ( alpha_1 = alpha_2 = 1/2)

Tr|Cap.|Combinación lineal ponderada 
--|--|--
2|0|![ind_inund_comb_tirante_area_tr_2_0](https://user-images.githubusercontent.com/41757755/57334796-6624fd80-70e6-11e9-8b2f-8e6d813e5e69.png)
2|100|![ind_inund_comb_tirante_area_tr_2_100](https://user-images.githubusercontent.com/41757755/57335311-cbc5b980-70e7-11e9-9dbb-2787c9cbbb3d.png)

**Comment by iaga** [comment]
El script que genera el indice de extremos para todos los periodos de retorno y todas las capacidades del drenaje:
\SIG\desarrollo\sig_megadapt\procesamiento\ii_extre_model\indice_inund_v2

La base de datos que se utilizará como insumo en el modelo MEGADAPT: 
**SIG\desarrollo\sig_megadapt\procesamiento\ii_extre_model\salida\bd_ageb_tr.csv**
contiene los datos normalizados por la función de valor (linea recta) para todos los periodos de retorno, para cada uno de los elementos de la combinación lineal ponderada:

AGEB_ID | tr2_h_0per | ... | tr2_h_100per | tr2_in_prop0 | ... | tr2_in_prop100|...|
tr500_h_0per | ...| tr500_h_100per | tr500_in_prop0 |...| tr500_in_prop100
-- | -- | -- | -- | -- | -- | -- | -- | -- | --|--|--|--|--|

h- representa el tirante
in_prop - la proporción de área inundada por AGEB

## Consideraciones para la implementación

- Los elementos de la combinación lineal ponderada se generaron por separado para tener la capacidad de modificar las ponderaciones directamente en el modelo: por el momento se considerarán pesos iguales para ambos criterios.

- La implementación en el código se hará con la posibilidad de elegir el escenario de funcionamiento del drenaje profundo, en términos de la capacidad de operación del drenaje. Se tomará como escenario típico una capacidad de drenaje de 75%.

@serranoycandela
