### ISSUE TITLE
Generar workbooks de Tableau y bancos de datos para la presentación del 20 de septiembre

### ISSUE THREAD

**Issue by iaga** [sostenibilidad-unam/SHV#151]
Con el objetivo de tener lista la presentación del 20 de septiembre, se generarán workbooks de Tableau, bancos de datos y gráficas de los distintos componentes del modelo MEGADAPT.

**Ruta de trabajo:**

\CARPETAS_TRABAJO\aestrada\megadapt\tableau

**Ubicación de los archivos:**

Archivo fuente: \CARPETAS_TRABAJO\aestrada\megadapt\tableau\workbooks
Banco de datos: \CARPETAS_TRABAJO\aestrada\megadapt\tableau\banco_datos
Gráficas: \CARPETAS_TRABAJO\aestrada\megadapt\tableau\figuras

**La resolución para las gráficas será full-HD:** 1920X1080

Nota: Por favor, nombrar los archivos de acuerdo con el componente que se está trabajando.

**Comment by yosunemiquela** [comment]
Ya quedó el workbook de escorrentía en dropbox @iaga

**Comment by yosunemiquela** [comment]
Ya quedaron las gráficas con los últimos comentarios que hicimos hoy @iaga @aleestrada

**Comment by iaga** [comment]
# Banco de datos: 

@serranoycandela, favor de indicar los nombres y las rutas de ubicación de los archivos, así como también el procesamiento para obtener el banco final y el archivo flooding_vulnerability.csv

## Generación del extracto
Carpeta de trabajo: \CARPETAS_TRABAJO\fserrano\dashboard_megadapt_tableau


1.- Generación del extracto **<ruta_nombre>** utilizando tableau prep. El extracto contiene la unión de los archivos ??? y la salida del modelo megadapt para diversos escenarios?

2.- Unión del extracto **<ruta_nombre>** con **<la capa??>**, se genera el extracto **extracto_final_septiembre_alc_geo**., a partir del promedio de las corridas?

El procesamiento se encuentra ubicado en la ruta: 

## Vulnerabilidad por inundaciones
Nombre del archivo:  flooding_vulnerability.csv 
Insumo : budget_subsidencia.csv | De la agregación de la base de resultados del modelo -> budget.csv  y la unión de valores de subsidencia normalizada  a partir de la función de valor logística [subsidencia.json] 

procesamiento: 

los campos 
- scarcity_index_exposure_n
- scarcity_index_sensitivity_n
- flooding_index_n
-flooding_vulnerability 


son normalizados y procesados de la siguiente manera
~~~
base['scarcity_index_exposure_n']=1-base['scarcity_index_exposure_n']
base['scarcity_index_sensitivity_n']=1-base['scarcity_index_sensitivity_n']
base['flooding_index_n'] = 1 - base['flooding_index_n']
base['flooding_vulnerability'] = np.power(base['flooding_index_n'],1-base['subsidencia_n'])
~~~

por lo cual el campo flooding_vulnerability es calculado como flooding_index_n elevado a la 1 - subsidencia_n 


@vichdzgeo podrías por favor colocar una descripción breve de la generación del archivo de inundaciones, así como también el banco de datos que utilizaste para generarlo, gracias.



## Agregación a nivel alcaldía

Nombre del archivo: alcaldias_budget_mean_norm.csv
Ubicación: carpetas_trabajo\fserrano\dashboard_megadapt_tableau\alcaldias_budget_mean_norm

Procesamiento: 
Del proceso anterior, la base de datos se agrega a nivel de alcaldía con el script "procesa_todo_alcaldia.py" de los cuales para cada alcaldía toma los agebs que le corresponden según el campo 'alcaldia' y calcula la media de todos los valores.

~~~
for a,b in zip(alcaldias,alcaldias_nom):
    for year in years:
        for budget in budgets:
            base_alc_pre =base.query('year=='+str(year)+'and sacmex__budget=='+str(budget)+'and alcaldia_abrev=="'+a+'"')
            nombre_alcaldia = base_alc_pre['alcaldia'].unique()
            vulnerabilidad = base_alc_pre['vulnerabilidad'].mean()
            exposicion_escasez = base_alc_pre['scarcity_index_exposure_n'].mean()
            vulnerabilidad_escasez = base_alc_pre['household_potable_water_vulnerability_n'].mean()
            exposicion_inundaciones = base_alc_pre['flooding_index_n'].mean()
            vulnerabilidad_inundaciones = base_alc_pre['flooding_vulnerability'].mean()
            salida_csv.write(a+","+b+","+str(year)+","+str(budget)+","+str(exposicion_escasez)+","+str(vulnerabilidad_escasez)+","+str(exposicion_inundaciones)+","+str(vulnerabilidad_inundaciones)+","+str(vulnerabilidad)+"\n")
~~~

@vichdzgeo podrías ayudarnos con la descripción de esta base de datos, por favor.

**Comment by iaga** [comment]
# Workbooks Tableau modelo MEGADAPT AGEB

Se desarrollaron una serie de workbooks de tableau con diferentes versiones. 



## Versiones previas

## Version finales

**Ubicación:** \CARPETAS_TRABAJO\aestrada\megadapt\tableau\workbooks\finales_hallie

### Insumos:

- Extracto: extracto_final_septiembre_alc_geo
- Cálculo de la vulnerabilidad por inundaciones: flooding_vulnerability.csv.

El extracto contiene los campos:

Campo|Archivo fuente
--|--|
Ageb Id|ageb_alc.csv
Alcaldia Num|ageb_alc.csv
Alcaldia Abrev|ageb_alc.csv
Poblacion|ageb_alc.csv
Pobreza Ageb|ageb_alc.csv
Alcaldia1|ageb_alc.csv
Pobreza Alc|ageb_alc.csv
Alcaldia|bd_pobreza_alc_cdmx_15.csv
Pobreza Alc Num|bd_pobreza_alc_cdmx_15.csv
Year|
Sacmex__Budget|
Censusblock Id|
Sewer Infrastructure Age|
Household Potable System Lacking Percent|
Resident Asset Index|
Flooding Event Count|
Flooding Index|
Ponding Event Count|
Scarcity Index Exposure|
Scarcity Index Sensitivity|
Household Potable Water Sensitivity|
Household Resilience|
Household Potable Water Vulnerability|
Household Sewer Intervention Count|
Holusehold Potable Water Intervention Count|
F1|flooding Vulnerability.csv
Censusblock Id (flooding Vulnerability.csv)|flooding_vulnerability.csv
Year (flooding Vulnerability.csv)|flooding_vulnerability.csv
Sacmex__Budget (flooding Vulnerability.csv)|flooding_vulnerability.csv
Flooding Vulnerability|flooding_vulnerability.csv
Vulnerabilidad|flooding_vulnerability.csv
Ageb Id1|megadapt_wgs84_pop.shp
Cvgeo1|megadapt_wgs84_pop.shp
Geometry|megadapt_wgs84_pop.shp

### Campos calculados

Los campos calculados necesarios para esta versión de las gráficas se describen a continuación.

Nombre|Descripción
--|--|
scarcity_wf|Índice de escasez invertido, (1-índice de escasez) categorizado con wf
Scarcity Index Exposure inv|1-Índice de exposición escasez
Scarcity Index Sensitivity inv|1-Índice de sensibilidad escasez
flooding_wf|Flooding vulnerability categorizada con wf
vulnerabilidad total|Combinación lineal ponderada de la exposición por escasez y por inundaciones, con el mismo peso para cada componente. 
vulnerabilidad_total_wf|El campo vulnerabilidad total categorizado con wf
pobreza_inv|1-Pobreza Alc Num
budget_filter|Filtro para los diversos budgets 


### Evolución en el tiempo, con diferentes presupuestos
Se utilizó el mismo tipo de Dashboard en tableau para presentar los resultados de las siguientes salidas del modelo:
1. Exposición por AGEB para escasez de agua, a partir del índice de exposición a la escasez de agua
2. Exposición por AGEB para Inundaciones, <Descripción por serranoycandela>
3. Riesgo socio-hidrológico por AGEB, campo calculado dentro de tableau: vulnerabilidad total.

Sheet|Nombre de la pestaña|Descripción
--|--|--|
Gráfica por AGEB|xxxx_ageb|La gráfica muestra el Índice de poder adquisitivo de los residentes contra la varible de interés (1- índice de exposición a la escasez, exposición a las inundaciones, riesgo socio-hidrológico). Los colores representan a la variable xxxx_wf. El tamaño de los círculos indica la población (4 categorías: 1k, 5k, 10k, 17k). Los detalles muestran el Ageb Id y el nombre de la Alcaldía (Alcaldia 1). Se filtra por buget y por Resident Asset Index (para dejar fuera los valores nulos). Pages contiene al campo Year.
Mapa por AGEB|xxxx_ageb_map|Mapa que muestra la exposición en categorías, utilizando xxxx_wf. Los detalles muestran únicamente el nombre de la Alcaldía (Alcaldia 1). Se filtra por budget. Pages contiene al campo Year.
Dashboard|xxxx_exp|Dashboard que contiene de lado izquierdo a la gráfica de exposición y de lado derecho el mapa, ambos con la misma escala de colores. En la franja derecha se muestra el control de Pages y la categorización del presupuesto (Muy bajo, bajo, moderado, alto, muy alto). 

#### Exposición: Escasez
Nombre del archivo: exposicion_escasez.twb
Definición del índice de exposición a la escasez de agua: 1-scarcity_exp = (w_zonas_crit)(fv_zonas_crit) + (w_dias_sagua)(fv_dias_sagua)+ (w_antiguedad)(fv_antiguedad) + (w_falta_dist)(fv_falta_dist) + (w_presion_hid)(fv_presion_hid), (ver issue https://github.com/sostenibilidad-unam/SHV/issues/147)

#### Exposición: Inundaciones
Nombre del archivo: exposicion_inundaciones.twb
Definición del índice de exposición a las inundaciones: <serranoycandela>

#### Riesgo socio-hidrológico
Nombre del archivo: vulnerabilidad_total.twb
Definición: Campo calculado vulnerabilidad_total, es decir, la combinación lineal ponderada de la exposición por escasez y por inundaciones, con el mismo peso para cada componente. 

Nota: los archivos ubicados en la misma carpeta, pero con terminación _fig, se utilizaron para ajustar las imágenes para la presentación powerpoint que se entregó al equipo socio-institucional.

**Comment by iaga** [comment]
# Workbook Tableau cuencas

@yosunemiquela, podrías por favor colocar una descripción breve de las imágenes que generaste, así como también los bancos de datos que utilizaste para generarlas, gracias.

**Comment by aleestrada** [comment]
# Workbooks Tableau modelo MEGADAPT Alcaldía

Se desarrollaron una serie de workbooks de tableau con diferentes versiones. 



## Versiones previas
La versión no cuenta con el formato final avalado por Luis.
**Ubicación**: \CARPETAS_TRABAJO\aestrada\megadapt\tableau\workbooks\finales_luis\escasez_exposicion_inequidad

## Versiones finales
La versión cuenta con el formato final avalado por Luis.
**Ubicación:** \CARPETAS_TRABAJO\aestrada\megadapt\tableau\workbooks\finales_luis\escasez_exp_ineq

### Insumos:

- Spatial file: Delegaciones.shp
- Agregación a nivel alcaldía: carpetas_trabajo\fserrano\dashboard_megadapt_tableau\alcaldias_budget_mean_norm.csv

### Campos calculados

Los campos calculados necesarios para esta versión de las gráficas se describen a continuación.

Nombre|Descripción
--|--|
Alcaldia Abrev (group)|Grupos realizados de acuerdo a los niveles de riqueza-pobreza de la CDMX. Se consideró el dato sobre la pobreza por alcaldía en la ciudad y se dividió en cuartiles.
budget_filter|Filtro para los diversos budgets 


### Contenido del archivo de tableau

Gráfica|Nombre del archivo|Descripción
--|--|--|
Exposición por alcaldía para Escasez de agua|exposicion_escasez|La gráfica ordena de mayor a menos el nivel promedio de exposición a escasez para las alcaldías de la CDMX. Los colores de las barras y círculos corresponden a los cuartiles de riqueza – pobreza de la ciudad; el azul más obscuro corresponde a las alcaldías más ricas, mientras que el azul más claro, a las alcaldías más pobres (de acuerdo a los datos publicados por el CONEVAL de pobreza municipal). Las divisiones horizontales muestran los cuartiles de exposición (0.25,0.50,0.75), dónde los niveles más cercanos al eje x muestran a las alcaldías con menor nivel de exposición.
Mapa de los niveles de escasez por alcaldía|mapa_esc_exp|Mapa del nivel de exposición promedio de escasez por alcaldía. Los colores del mapa corresponden a los colores de las bandas horizontales de la gráfica de exposicion-escasez.

**Comment by yosunemiquela** [comment]
# Workbooks Tableau modelo MEGADAPT Escorrentía/Cuencas

Se generó un workbook en tableau: 
**Ubicación**: 
\CARPETAS_TRABAJO\aestrada\megadapt/tableau/workbooks/perdida_forestal_cuencas_MEGADAPT.twb

Se utilizaron los siguientes insumos:
# Insumos:

- Cobertura forestal, agrícola y urbana por cuenca: SIG/desarrollo/sig_megadapt/procesamiento/tableau/banco_datos/database_forestal_agricola_cuencas_Changes.xlsx
- Escurrimiento superficial promedio por cuenca para cada escenario de crecimiento urbano: 
\CARPETAS_TRABAJO\aestrada\megadapt/tableau/banco_datos/balance_wide_tableau_corrected.xlsx

### Campos calculados

Se calcularon los siguientes campos:

Nombre|Descripción
--|--|
Pérdida de cobertura forestal (km2)|Proporción de área forestal proyectada al 2040 para cada cuenca. Para calcularlo se dividió el área de cobertura forestal proyectada al 2040 entre el área total de la cuenca|Pérdida agrícola (km2)
Pérdida de cobertura agrícola (km2)| Proporción de área agrícola proyectada al 2040 para cada cuenca. Para calcularlo se dividió el área de cobertura agrícola proyectada al 2040 entre el área total de la cuenca

### Respuesta hidrológica en función del cambio de cobertura proyectado al 2040
Descripción|Nombre
--|--|
Mapa de subcuencas altas de la Ciudad de México. Los colores del mapa corresponden a los grupos de cuencas con crecimientos urbanos proyectados al 2040 diferenciados en función de la Gráfica | cuencaslocal_dispersion_titulo.png
Gráfica que muestra cambio de cobertura del 2014 al 2040 a nivel de cuenca. El tamaño de los círculos representa el tamaño de la cuenca (km2). La línea de tendencia representa el promedio global de cambio de cobertura esperado al 2040| cuencaslocal_dispersion_titulo.png
Gráfica de barras apiladas que muestra la cobertura en los tres principales tipos: forestal, agrícola y urbano para el 2014 y el 2040|cambio_cobertura_agricola_forestal_tituloV4.png
Gráfica que muestra la respuesta hidrológico (hectómetros cúbicos) a nivel de cuenca bajo condiciones urbanas del 2014 y proyectadas al 2040 |respuesta_hidrologicaV2_titulo.png

ya quedó @iaga
