### ISSUE TITLE
Generar índice de escasez final con correcciones de Hallie

### ISSUE THREAD

**Issue by aleestrada** [sostenibilidad-unam/SHV#153]

**Comment by aleestrada** [comment]
# Descripción:
Se realiza una nueva versión del índice de escasez en el que se consideran las correcciones realizadas por Hallie a las variables que se incluyeron en cada uno de los índices (exposición y sensibilidad) en la junta del 26 de septiembre.

# Insumo

Issue #100

# Producto
- [x] Capa del índice de exposición ante escasez
- [x] Capa del índice de sensibilidad ante escasez

# Ubicación:
\SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\final\producto_v2

**Comment by aleestrada** [comment]
# Insumos Finales

Num|Insumo|Archivo|Descripción|Ruta
--|-- | -- | -- | --
1|Densidad de población | den_pob_17_ageb.shp | Densidad de población por km^2 para el año 2017 | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\final\insumos\den_pob
2|Zonas críticas | agebs_tandeo.shp | Proporción de la AGEB cuyas viviendas tienen menos de 4 horas de agua al día | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\final\insumos\zonas_crit
3|Ingreso | income_pc.shp | Índice de poder adquisitivo (asset index), como *proxy* del ingreso por AGEB |\SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\final\insumos\income_pc
4|Días sin agua | tp_dsa_agebs_cdmx_v3.shp | Número promedio de días sin agua por AGEB, de acuerdo a los reportes | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\final\insumos\dias_sagua
5|Falta en la distribución | falta_dist.shp | Proporción de viviendas sin conexión a la red de agua | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\final\insumos\viviendas_sagua
6|Cisternas | cisternas_viv.shp | Número de cisternas por AGEB | \SIG\desarrollo\sig_megadapt\procesamiento\indice_escasez\final\insumos\cisternas


# Cálculo de funciones de valor

Num|Función de valor|Parámetros|Desc.
--|-- | -- | -- |
1|**Densidad de población**: fv_pob_ageb ![imagen](https://user-images.githubusercontent.com/41757755/60528028-224f0e80-9cb9-11e9-9af9-813a941d4ba4.png) Logística invertida| a=0.3, centro= 150, max = max (x_pob)*| Densidad de población por km^2 (AGEB)
2|**Zonas críticas**: fv_zonas_crit ![imagen](https://user-images.githubusercontent.com/41757755/60525713-84f1db80-9cb4-11e9-82ec-50cbd2a3efd2.png) Campana | a=23, centro= 0, max = max (datos_AGEB$critico)*| Proporción de la AGEB cuyas viviendas tienen menos de 4 horas de agua al día
3|**Ingreso**: fv_ingreso ![image](https://user-images.githubusercontent.com/25159102/66064522-29312b80-e50b-11e9-9eca-003b4cbddb5c.png) Logística |a=0.12, center=0.6,max = max (x_ingreso)*|Índice de poder adquisitivo por AGEB (assets index) como *proxy* del ingreso | 
4|**Días sin agua**: fv_dias_sagua ![imagen](https://user-images.githubusercontent.com/41757755/60526288-a4d5cf00-9cb5-11e9-80ba-627ac8f416d5.png) Campana | a=15, centro=0, max=max(x_dias_sagua)* | Número promedio de días sin agua por AGEB, de acuerdo a los reportes |
5|**Falta en la distribución (viviendas sin agua)**: fv_falta_dist  ![imagen](https://user-images.githubusercontent.com/41757755/60528689-99d16d80-9cba-11e9-8300-63374d0b71fa.png) Campana| a=20, centro=0, max=max(x_viviendas_sagua)* | Proporción de viviendas sin conexión a la red de agua |
6|**Cisternas**: fv_num_cisternas ![imagen](https://user-images.githubusercontent.com/41757755/60525896-e44feb80-9cb4-11e9-8e04-e834487c4f7d.png) Convexa creciente| gamma= 0.16, max= 7948 | Número promedio de cisternas por vivienda a nivel delegación para cada AGEB |


Nota: El valor máximo se refiere al máximo para todas las AGEBS, para todo el periodo de simulación. 

*Estas variables no se actualizan a lo largo de la simulación, por lo que no es necesario calcularlo cada time-step.

# Índice de escasez (exposición)
scarcity_exp = (w_zonas_crit)(fv_zonas_crit) + (w_dias_sagua)(fv_dias_sagua)+ (w_falta_dist)(fv_falta_dist)

# Índice de escasez (sensibilidad)
scarcity_sens = (w_pob_ageb)(fv_pob_ageb) + (w_ingreso)(fv_ingreso)

# Índice de escasez (capacidad adaptativa), sin precariedad hídrica
scarcity_cap = (w_cisternas)(fv_cisternas)

## Representación del índice de vulnerabilidad:

1 - No vulnerable, no existe escasez
0 - Vulnerable, existe escasez

**Comment by aleestrada** [comment]
@serranoycandela ya se tiene el nuevo script, así como las nuevas capas de los índices de exposición y sensibilidad ante escasez de agua, para que puedan ser incorporados al modelo general.

**Comment by iaga** [comment]
# Revisión del modelo AHP 

En la reunión del 11 de Noviembre con Luis se realizó una revisión de los pesos del modelo multicriterio de la red de Escasez que sirve como insumo para el modelo MEGADAPT. Se observó que el vector de prioridades contiene pesos de ceros para los elementos del bloque socio-institucional, por lo que se realizaron las siguientes actividades:

- Revisión de la supermatriz. 
  - Se determinó que la supermatriz contiene la ponderación de los clusters, con pesos diferentes para cada uno de los clusters. 
  - Se realizó un ejercicio en excel para generar los pesos de los criterios considerando que los clusters tienen pesos idénticos
 - Se compararon ambas supermatrices

- Generación de otra versión del modelo multicriterio. 
  - Dicha versión considera que los pesos de los clusters son idénticos para todos los elementos de la red

**Comment by iaga** [comment]
@vichdzgeo

**Comment by aleestrada** [comment]
En junta con Luis y Fidel se decidió no descartar de la parte de la exposición, la presión hidráulica y tomar como mocelo índice el del issue #147, considerando la desagregación entre exposición, sensibilidad y capacidad adaptativa.

**Comment by iaga** [comment]
# Índices finales

# Índice de escasez (exposición)
scarcity_exp = (w_zonas_crit)(fv_zonas_crit) + (w_dias_sagua)(fv_dias_sagua)+ (w_falta_dist)(fv_falta_dist) + + (w_falta_dist)(fv_falta_dist) + (w_presion_hid)(fv_presion_hid)

# Índice de escasez (sensibilidad)
scarcity_sens = (w_pob_ageb)(fv_pob_ageb) + (w_ingreso)(fv_ingreso)

# Índice de escasez (capacidad adaptativa), sin precariedad hídrica
scarcity_cap = (w_cisternas)(fv_cisternas)

## Representación del índice de vulnerabilidad:

1 - No vulnerable, no existe escasez
0 - Vulnerable, existe escasez
