### ISSUE TITLE
definir cuantos y cuales escenarios de precipitación se usarán

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#24]

**Comment by yosunemiquela** [comment]
realizamos un análisis exploratorio para definir el modelo climático y los escenarios de precipitación a utilizar. De acuerdo a los productos entregados por Vivoni, se identificaron dos produtos disponibles: WorldClim y hamann que se diferencian en cuanto a los periodos de proyección climática. Se optó por el uso del produto Hamman ya que los periodos de proyección (2040-2069, 2070-2099) son compatibles con los escenarios de crecimiento urbano. El producto Hamann contiene proyecciones generadas por 2 modelos de circulación global (MCG) (HADGEM2-ES y MPI-ESM-LR). Cada MCG contiene proyecciones climáticas bajo dos escenarios de cambio climático de acuerdo al IPCC RCP: 8.5 y 4.5.
Se hicieron gráficas para comparar las proyecciones y elegir, con base en esta información, el modelo de circulación a utilizar.

Proponemos usar el MCG  HADGEM2-ES para los dos escenarios RCP 8.5 y 4.5 proyectados.
@serranoycandela 
![cambioclimaticonf_zmvm](https://user-images.githubusercontent.com/25304777/45180468-1ac9f080-b1e1-11e8-9410-36d9f6d82bb1.png)

**Comment by yosunemiquela** [comment]
A partir de los datos climáticos albergados en el cluster "Climaticos" con información climática proyectada, se generaron promedios mensuales para los dos periodos de interés. Se calcularán las diferencias con los promedios historicos para calcular las diferencias. Las diferencias se utilizarán para generar series de tiempo de las variables climáticas de interés para los escenarios seleccionados.
