### ISSUE TITLE
entender la estructura de datos y el procedimiento que usaron Vivoni y sus coloboradores para calcular la curva numérica

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#28]

**Comment by vichdzgeo** [comment]
Los insumos necesarios para la asignación de la curva numérica son los siguientes:

Capa de subcuencas y bandas de elevación. -> sw_eb
Capa de cobertura de suelo -> cb_s
Capa de tipo de suelo (clasificada en grupos de suelo hidrologicos SCS - FAO ) ver el documento de Appendices en la página 17 -> tp_s
Para el cálculo de la curva numérica se realiza lo siguiente:

Se realiza una intersección entre la capa sw_eb y la capa cb_s. La salida de este proceso genera una capa que contiene polígonos con atributos relacionados a la subcuenca correspondiente, numero de banda de elevación y tipo de cobertura. -> sw_eb_i_cb_s
Con la capa de salida del proceso anterior sw_eb_i_cb_s se realiza una intersección con la capa tp_s el resultado será una capa que contenga en sus atributos la el numero de subcuenca,la banda de elevación, la cobertura y el tipo de suelo. -> sw_cb_t

Para asignar el valor de la curva numérica se realiza un proceso condicional que depende de la cobertura del suelo y el tipo de cobertura. ver el documento de Appendices en la página 20.

Se calcula el porcentaje de area según el tipo y cobertura del total del area de la banda de elevación perteneciente a cada subcuenca y se multiplica por el número de curva asignado en el paso anterior.

Con el dato anterior se realiza un promedio ponderado del valor de la curva numérica.
