### ISSUE TITLE
calcular las escorrentías con los números de curva actuales para cada cuenca swat

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#29]

**Comment by yosunemiquela** [comment]
El modelo ya se implementó. la ruta es:
CARPETAS_TRABAJO/ymiquelajauregui/Escorrentia/escorrentiaV2.R
Ya se generaron las escorrentías diarias. 
Faltaría documentar a detalle el script y definir la estructura de los datos de salida
@serranoycandela

**Comment by yosunemiquela** [comment]
La base de datos de escorrentías diarias para las 244 cuencas se encuentra en:
CARPETAS_TRABAJO/ymiquelajauregui/Escorrentia/Escorrentias.RData
@serranoycandela

**Comment by yosunemiquela** [comment]
El día 13 de noviembre 2018 se volvió a realizar un ejercicio de prueba para verificar consistencia en el modelo.
la idea era verificar a qué se debía la variabilidad anual en escorrentía en una cuenca determinada que observamos en los mapas de escorrentía agregados en la última reunión de MEGADAPT.
La hipótesis a evaluar es que las diferencias anuales son resultado de la acumulación de días en los que se rebasa un umbral (0.2*Si) en el que Si es la retención de humedad del suelo. Se graficó la precipitación diaria para la cuenca 32 (identificada con mayores cambios anuales) para los años 2010 y 2013. Se volvió a correr el modelo SWAT para el periodo 2010-2013 y se contaron las veces que se rebasaba el umbral. Para el 2010 solamente 8 días al año se rebaso el umbral. Para el 2013 38 días.

![preciptacion2010_2013](https://user-images.githubusercontent.com/25304777/48433835-c0e42a80-e73d-11e8-87e8-8d3c46b0c333.jpeg)
