### ISSUE TITLE
revisar los datos extraidos de evapotranspiración y precipitación

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#30]

**Comment by yosunemiquela** [comment]
Ya revisé los datos de precipitación y evapotransipración. Generé un par de gráficas para comparar los rangos de las variables con la base de datos de Vivoni.
Se observaron consistencias en los patrón histórico para la evapotranspiración y precipitación
@serranoycandela @vichdzgeo
