### ISSUE TITLE
Ajustar la regresión en R para el modelo de encharcamientos

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#34]
Objetivo: Generar un modelo estadístico que describa los encharcamientos de la Ciudad de México.

La carpeta provisional dónde se encuentran los modelos es:
CARPETAS_TRABAJO/aestrada/megadapt/ench_inund_model

Posterior al análisis de los datos (issue #35), se decidió en una reunión con @serranoycandela e @iaga, que los encharcamientos se modelarían mediante un panel espacial.

**Comment by aleestrada** [comment]
Posterior al análisis de los datos, se decidió en una reunión con @serranoycandela e @iaga, que los encharcamientos e inundaciones se modelarían mediante un panel espacial.

**Comment by aleestrada** [comment]
Se modelaron la frecuencia de inundaciones y encharcamientos mediante le uso de modelos de panel. Los modelos se realizaron considerando los datos de las variables en niveles, así como las delthas (cambios) calculadas por Fidel. El análisis se dividió en dos:
- Modelo de toda CDMX
- Modelo por cluster

**Comment by AlfMedina** [comment]
Se generó el markdown que contiene el método jerárquico utilizado para crear los clusters. La distancia utilizada es "canberra". Se definieron cinco clusters, a partir del dendrograma:

![treeplot](https://user-images.githubusercontent.com/22686851/47047650-bdb94700-d15d-11e8-8318-3ae5f69375b1.png)

Ruta: SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\clusters

**Comment by iaga** [comment]
La capa del modelo jerárquico:

![clusters5_allvar](https://user-images.githubusercontent.com/41757755/47047712-ee997c00-d15d-11e8-8e7a-437dcc272e3d.png)


A partir de la capa, se utilizó el script: build_dataframe.py para generar el archivo: agebs_data_ja_jerar.csv, el cual contiene los datos necesarios para correr el panel en el formato requerido por R. Dichos campos son:

ageb_id | ja_id | year | class | f_inunda | f_charcos | preci | elevacion | capacidad | escorren
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by iaga** [comment]
Resultados del modelo de panel de encharcamientos de efectos aleatorios en el tiempo

Cluster|R^2
---|---
1|0.09607
2|0.12989
3|0.1213
4|0.10397
5|0.13051

Para la parte espacial, el modelo pasó la prueba de Lagrange  únicamente para dos clusters.

**Comment by aleestrada** [comment]
En la reunión del día de hoy con Luis, se tuvieron los siguientes acuerdos, para el modelo de inundaciones y encharcamientos:
- El objetivo del modelo es: emular los encharcamientos e inundaciones observadas, de forma tal que el actor pueda tomar decisiones y el modelo varíe.
- Se considerarán tres opciones de modelación:
  1. El modelo de panel espacial que considera los cluster obtenidos mediante k-means.
  2. Se realizará un modelo utilizando los clusters de las 16 regiones realizadas por Yosune, tanto para encharcamientos, como para inundaciones. 
@yosunemiquela proporcionará los datos de las AGEB's que pertenecen a cada una de estas regiones.
  3. Modelo bayesiano de encharcamientos e inundaciones.
- Estos acuerdos se comunicarán en la reunión del lunes.

**Comment by aleestrada** [comment]
Es necesario revisar la parte de la prueba de raíces unitarias del modelo, ya que se estaba aplicando la prueba de **Augmented Dickey Fuller**, sin embargo esta prueba es para probar estacionariedad en una sola serie, no en el panel de datos.
@iaga

**Comment by yosunemiquela** [comment]
Ya quedaron los nuevos grupos que se generaron a partir de las frecuencias y precipitación agregadas para 2007-2014 tanto para los datos de encharcamientos como de inundaciones.
El script y los datos están en:
MEGADAPT/mega_procesamiento/banco_datos/encharcamientos_agebs/tablas_contingencia

**Comment by iaga** [comment]
Utilizando el markdown **clusters_tabla_contingencia.Rmd** se generaron los archivos que contienen los 16 clusters (a partir de las tablas de contingencia):

- **cluster_inunda_tabcont.csv**
- **cluster_ench_tabcont.csv**

Ruta:

SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/grupos_tabla_contingencia

**Comment by iaga** [comment]
@aleestrada e @iaga generaron las capas temporales para encharcamientos **clusters_ench_tabla_cont.shp** e inundaciones **clusters_ench_tabla_cont.shp**. Los mapas obtenidos:

![clusters_ench_tabla_cont](https://user-images.githubusercontent.com/41757755/47446160-40ef2400-d780-11e8-8703-136b367c991f.png)
![clusters_inund_tabla_cont](https://user-images.githubusercontent.com/41757755/47446163-4482ab00-d780-11e8-8c22-4e9d78b42ab4.png)

Se encuentran en la ruta:

SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/grupos_tabla_contingencia

**Comment by iaga** [comment]
Se realizó una segunda versión del script **build_dataframe.py** para utilizar la capa anterior (se incluyeron dos columnas extra, una para el cluster de encharcamientos y otra para el cluster de inundaciones). El nuevo archivo se llama **build_dataframe_v2_iaga.py**.

Ruta:

SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/

**Comment by iaga** [comment]
El archivo **agebs_data_ja_kmeans_tabla_con.csv** inlcuye los 16 clusters para encharcamientos e inudaciones (fue generado con el script **build_dataframe_v2_iaga.py**). Las columnas que contiene:

ageb_id | ja_id | year | class_ench | class_in | f_inunda | f_charcos | preci | elevacion | capacidad | escorren
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Se encuentra en la ruta:

SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/

**Comment by aleestrada** [comment]
Acuerdos de la reunión del 25 de octubre:

- Se normalizarán las variables que se considerarán en el modelo, de acuerdo al criterio que se siguió con la variable precipitación.
- Se considerará el promedio del periodo analizado para el análisis de regresión.
- El análisis de regresión se realizará con los clusters definidos por Luis, en la junta, de acuerdo a las características de precipitación y flujo del agua en las zonas de la CDMX. @serranoycandela será el encargado de proporcionar los AGEBs que pertenecen a cada cluster.

**Comment by iaga** [comment]
# Datos para la regresión con los nuevos clusters 

## Insumos
@serranoycandela y @vichdzgeo generaron la capa **agebs_cuencas_cdmx_v1.shp** que contiene los clusters definidos en la reunión anterior (ver issue #72). La capa contiene los siguientes campos:

AGEB_ID | cvgeo| Join_Count | TARGET_FID| FID_1| region
-- | -- | -- | -- | -- | --

## Generación de los nuevos datos

A partir de los datos normalizados **agebs_data_normalizados.csv** se generó el archivo **agebs_data_norm_prom_clust.csv** que se utilizará como insumo para las regresiones.

**Comment by iaga** [comment]
# Modelo para encharcamientos e inundaciones con los nuevos grupos definidos por los expertos

## Panel

A partir de los datos, se observa que existen ciertos clusters asociados con la escorrentía y otros no. Por lo tanto, los modelos se divideron en dos clases: con escorrentía **ce**  y sin escorentía **se**.

### Encharcamientos
Para el caso de encharcamientos se obtuvieron los siguientes resultados:

cluster_ce|Fijos|Pool|Random|Random_time|Fixed_time
---|---|---|---|---|---
1|0.103|**0.28**|0.10|0.18
2|0.107|0.11|0.05|**0.13**
3|0.07|**0.22**|0.12|0.14
6|0.06|.06|.08|**0.17**
7|0.02|**0.37**|0.26|0.30

cluster_se|Fijos|Pool|Random|Random_time|Fixed_time
---|---|---|---|---|---
4|0.0104|0.05|0.05|**0.12**
5|0.146|0.14|0.06|**0.18**
8|**0.15**|0.14|0.04|0.09
9|**0.10**|0.08|0.06|0.08

Los cuales indican que se necesitan distintos tipos de modelos según el tipo de cluster.

### Inundaciones

Para el caso de inundaciones se obtuvieron los siguientes resultados:

cluster_ce|Fijos|Pool|Random|Random_time
---|---|---|---|---
1| -0.158|**0.054**|0.021|0.050
2|-0.125|0.007|0.014|**0.059**
3| -0.109|0.071|**0.12**|0.062
6| -0.153|0.009|0.049| **0.061**
7|-0.075|0.129|0.008|**0.152**

cluster_se|Fijos|Pool|Random|Random_time
---|---|---|---|---
4|-0.166|0.002|0.0009|**0.061**
5|-0.159|0.030|0.012|**0.045**
8|-0.123|0.032|0.015|**0.132**
9|-0.146|0.031|0.020|**0.033**

**Comment by aleestrada** [comment]
Se revisaron los datos de capacidad y se identificaron, principalmente, dos puntos extremos, con una capacidad de entre  1000 y 2000. Posteriormente se tuvo una reunión con Fidel, para revisar de nuevo los puntos extremos y se acordaron los siguientes puntos:
- Se revisará la capa de la red de drenaje.
- Se revisará el cálculo de la capacidad de drenaje.
- El hecho de que una AGEB cuente con algún tubo de la red de drenaje no significa que capture el agua que cae en la AGEB. Es necesario analizar más este punto.
- Se calculará la centralidad.
- Por el momento se detendrá el análisis de regresión para los encharcamientos, utilizando los promedios por cluster (ya se tiene un avance en este sentido y ya se realizaron las regresiones para el caso del panel).

**Comment by iaga** [comment]
# Revisión del mapa de subsidencia

Objetivo: Revisar el mapa de subsidencia para observar la relación entre inundaciones/subsidencia, ya que las regresiones realizadas hasta el momento para inundaciones no logran reflejar el fenómeno.

Insumos: La capa de subsidencia se encuentra ubicada en la ruta MEGADAPT\mega_procesamiento\input_modelos\modelo_escasez\subsidencia_cdmx

![mapa_subsidencia](https://user-images.githubusercontent.com/41757755/48018809-72a8a900-e0f7-11e8-96c0-ed8afdd337de.png)

**Comment by iaga** [comment]
@serranoycandela tenemos dudas sobre la capacidad de desalojo que se está utilizando en el modelo. El archivo de python (build_dataframe.py) utiliza la capa **agebs_df_Q.shp**, la cual contiene la variable **Q100**. La pregunta es si se está utilizando la capacidad de desalojo del drenaje profundo o la del drenaje primario. ¡Gracias!

**Comment by serranoycandela** [comment]
la capa de drenaje primario que use para generar el Q100 incluye el drenaje primario y el drenaje profundo

**Comment by aleestrada** [comment]
Derivado del análisis de la capacidad de desalojo, se acordó en junta con @serranoycandela e @iaga que es necesario extender el cálculo de la precipitación, de tal forma que se considere no sólo los milímetros de lluvia, sino también el área en que precipita, para obtener el volumen total de lluvia que tiene el AGEB.
