### ISSUE TITLE
Analizar los datos de precipitación y escorrentias y capacidad de desalojo para decidir que tipo de regresión se aplicará

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#35]

**Comment by iaga** [comment]
Se sugiere revisar el artículo: "Bayesian Modeling of Flood Frequency Analysis in Bangladesh Using Hamiltonian Monte Carlo Techniques" ( Water 2018, 10(7), 900; https://doi.org/10.3390/w10070900) para tomar ideas sobre la simulación de inundaciones.

**Comment by iaga** [comment]
@aleestrada

**Comment by iaga** [comment]
Para el análisis geoespacial descargar el software GeoDa:

https://spatial.uchicago.edu/software

**Comment by iaga** [comment]
@AlfMedina @JosueMA

**Comment by iaga** [comment]
Para realizar la correlación espacial, es necesario realizar el spatial join de las frecuencias de inundación/encharcamiento con el resto de las variables que se utilizarán en el modelo @aleestrada

**Comment by iaga** [comment]
@serranoycandela elaboró el script en R que genera las gráficas en 3D para los años 2007-2013 (variables utilizadas: precipitación, capacidad de desalojo, encharcamiento/inundación): 3dplot.R

Además, generó un archivo csv que contiene el conjunto de todas las variables requeridas por R para hacer la regresión pertinente:  ageb_data.csv
El archivo contiene las siguientes columnas:
ageb_id | ja_id | year | f_inunda | f_charcos | preci | elevacion | capacidad | escorren






Ruta: MEGADAPT/mega_procesamiento/banco_datos/encharcamientos_escorrentias

**Comment by iaga** [comment]
El procesamiento de la capa de capacidad de desalojo y su documentación se encuentra en el issue #37, generada por @edithvilla

**Comment by serranoycandela** [comment]
ensamblé una nueva base de datos en la que la escorrentía se asigna a un ageb solo la cuenca de J.A. a la que pertenece contiene cuencas swat con escorrentías asociadas

es decir que los agebs centrales les asigné escorrentía 0 y solo los agebs de las periferias se les asigna una escorrentía, además se multiplicó los resultados de swat que salen en mm por año por el area de cada cuenca swat por lo que los nuevos datos de escorrentía están en litros por año

el nuevo csv está en:

MEGADAPT/mega_procesamiento/banco_datos/encharcamientos_escorrentias/agebs_data_ja.csv

**Comment by AlfMedina** [comment]
Los archivos (.Rmd y .html) de comparaciones por pares entre encharcamientos, inundaciones, precipitación y capacidad de desalojo se encuentran temporalmente en:
\CARPETAS_TRABAJO\amedina\ench_exp.Rmd

**Comment by iaga** [comment]
Utilizando el paquete "attribute based clustering" de Q-gis, se generó la capa temporal "promedios2", la cual contiene las siguientes columnas:

AGEB_ID | charc_mean | Q100_s | inun_mean | esc_mean| p_mean | class | ELEVACION | eleva
-- | -- | -- | -- | -- | -- | -- | -- | --

![clusters_prom2](https://user-images.githubusercontent.com/41757755/46696975-27bf7280-cbd9-11e8-9201-1b8e243aeeea.png)

Ruta:
SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias

**Comment by iaga** [comment]
@serranoycandela generó el archivo agebs_data.csv, el cual contiene los datos en el formato adecuado para R (para cada ageb, los años correspondientes). 
 
ageb_id | ja_id | year | f_inunda | f_charcos | preci | elevacion | capacidad | escorren
-- | -- | -- | -- | -- | -- | -- | -- | --

Ejemplo: 
ageb_id | ja_id | year 
-- | -- | ---
5959 | 72 | 2007
5959 | 72 | 2008
5959 | 72 | 2009
5959 | 72 | 2010
5959 | 72 | 2011
5959 | 72 | 2012
5959 | 72 | 2013


Ruta:
MEGADAPT/mega_procesamiento/banco_datos/encharcamientos_escorrentias

**Comment by AlfMedina** [comment]
Como resultado de la reunión con Luis, se solicitó realizar la identificación de los puntos extremos; a continuación se presentan los resultados de la búsqueda:


![puntos](https://user-images.githubusercontent.com/22686851/47032446-ff36fb80-d137-11e8-9c3d-fb239293094b.png)

**Comment by iaga** [comment]
![ageb_8253](https://user-images.githubusercontent.com/41757755/47036218-9c4a6200-d141-11e8-9d4d-00e0aa09a490.png)

**Comment by serranoycandela** [comment]
camaradas, noté que en la asociación de agebs a cuencas JA había algunas inconsistencias. Así que los calculé de nuevo ahora utilizando los centroides de cada ageb. La capa nueva se llama agebs_cuencas_ja_v2.shp

Está modificación tiene repercusiones en varios conjuntos de datos que hay que volver a ensamblar, afortunadamente todo está en scripts

Ruta:
SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias
![screen shot 2018-10-16 at 4 13 53 pm](https://user-images.githubusercontent.com/12860576/47047901-89925600-d15e-11e8-8b13-2d86a2caee31.png)

**Comment by serranoycandela** [comment]
ya recalculé las escorrentias usando la capa agebs_cuencas_ja_v2.shp

el resultado es  agebs_escorrentia_ja_v2.shp

cuendo vuelvan a ensamblar los csvs usando el script build_dataframe.py hay que usar esta versión

Ruta:
SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias

**Comment by serranoycandela** [comment]
La capa agebs_cuencas_ja_v2.shp contiene todos los agebs de la region de estudio hice una tercer versión que solo tiene los del DF

La capa nueva se llama agebs_cuencas_ja_v3.shp

Ruta:
SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias

**Comment by aleestrada** [comment]
@yosunemiquela en la carpeta que se menciona en este issue podrás encontrar los datos de precipitación acululada y normalizada por AGEB.

**Comment by iaga** [comment]
A partir del script **build_dataframe.py** desarrollado por @serranoycandela (el cual contiene los datos en el formato adecuado para R) se generó el archivo: **agebs_data_ja_kmeans_v2.csv**, el cual contiene las capa nueva **agebs_cuencas_ja_v3.shp** y las nuevas escorrentías **agebs_escorrentia_ja_v2.shp**

Ruta:
SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias
