### ISSUE TITLE
correr una prueba en el cluster y medir el tiempo

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#38]

**Comment by rgarcia-herrera** [comment]
BEGIN PROFILING DUMP
Sorted by Exclusive Time
Name                                                           Calls Incl T(ms) Excl T(ms) Excl/calls
MUTATE_HORIZONTALSTRATEGIES        70000  21055.246  21055.246      0.301
GO                                                               2000  53173.358  19043.653      9.522
MUTATE_VERTICALSTRATEGIES             70000  10422.671  10422.671      0.149
REPLICATE-TURTLES                                 2000    107.091   2651.788      1.326

Sorted by Inclusive Time
GO                                                               2000  53173.358  19043.653      9.522
MUTATE_HORIZONTALSTRATEGIES        70000  21055.246  21055.246      0.301
MUTATE_VERTICALSTRATEGIES             70000  10422.671  10422.671      0.149
REPLICATE-TURTLES                                 2000    107.091   2651.788      1.326

Sorted by Number of Calls
MUTATE_HORIZONTALSTRATEGIES        70000  21055.246  21055.246      0.301
MUTATE_VERTICALSTRATEGIES             70000  10422.671  10422.671      0.149
GO                                                               2000  53173.358  19043.653      9.522
REPLICATE-TURTLES                                 2000    107.091   2651.788      1.326
END PROFILING DUMP

**Comment by abaezacastro** [comment]
21 seconds MUTATE_HORIZONTALSTRATEGIES
10 seconds MUTATE_VERTICALSTRATEGIE
10.7 seconds REPLICATE-TURTLES
41.7 seconds total time site selection
