### ISSUE TITLE
terminar modelo de escasez

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#41]

**Comment by aleestrada** [comment]
Se modeló la escasez siguiendo un modelo Zero Inflated Negative Binomial, en sus versiones frecuentista y bayesiano.
Los resultados se encuentran en MEGADAPT/mega_procesamiento/input_modelos/modelo_escasez/scripts/escases_v3.Rmd

![image](https://user-images.githubusercontent.com/25159102/44753219-f4ba9700-aae2-11e8-94bc-fffb0ff458bf.png)

**Comment by aleestrada** [comment]
Dados los resultados de los modelos Zero Inflated Negative Binomial tanto frecuentista como bayesiano, y dada la naturaleza y distribución espacial de los datos analizados, se decidió dividir el análisis de, de tal forma que se capturen las diferentes dinámicas de la escasez de agua en la ciudad. En este sentido el análisis se dividió en dos:
- Zonas críticas:  Análisis de las zonas en la que los AGEB's presentan falta de agua de forma recurrente. Esta dinámica se modelará utilizando la variable de 
$$ días_sin_agua ~ zonas_criticas+antiguedad$$

**Comment by aleestrada** [comment]
Se corrieron los nuevos modelos y se agregó la variable de ingreso.

Sin embargo, éstos modelos no presentan un mejor ajuste que le que ya se tenía anteriormente.

Se tiene los siguientes comentarios:

1. El modelo que mejor ajusta es aquel que modela las zonas críticas para toda la Ciudad de México.
$$lambda ~ CRITICO+ANTIGUEDAD | V_SAGUA$$
2. Se requiere realizar un análisis más profundo, ya que si bien el modelo ajusta a los datos, se considera que no modela adecuadamente la heterogeneidad extrema de la Ciudad.
3. Se propone realizar un modelo multinivel bayesinano, con el objetivo de capturar la heterogeneidad de la CDMX. Sin embargo, es importante considerar que esta opción requiere un mayor tiempo de anáñisis y de estimación.

**Comment by aleestrada** [comment]
## Inclusión al modelo de la estracción de agua de pozos

- Se incluirá en el modelo de escasez el bombeo de pozos. Esto será mediante el número de pozos por AGEB los cuales tienen un valor constante de extracción, esta información será proporcionada por @edithvilla.
- La extracción de agua de pozos, a su vez afecta de forma positiva en los niveles de subsidencia de la AGEB. Es necesario considerar esto en el modelo.

## Modelación de eventos extremos

- De acuerdo a la reunión que se tuvo con Luis, se modelarán los eventos extremos de escasez.

**Comment by edithvilla** [comment]
La capa de pozos está lista (número de pozos por ageb) issue #965 del repositorio de Planeación Colaborativa
