### ISSUE TITLE
Hacer un script para preparar las capas de urbanización para ser usadas en el recálculo del número de curva.

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#55]

**Comment by serranoycandela** [comment]
el resultado deben ser shapes binarios de urbanización para todos los años que arroja el modelo

**Comment by serranoycandela** [comment]
PROBABILITY_COLOR=   0,    50,         , #transparent
PROBABILITY_COLOR=   50,   60, 0X005A00, #0, 90,0 dark green
PROBABILITY_COLOR=   60,   70, 0X008200, #0,130,0
PROBABILITY_COLOR=   70,   80, 0X00AA00, #0,170,0
PROBABILITY_COLOR=   80,   90, 0X00D200, #0,210,0
PROBABILITY_COLOR=   90,   95, 0X00FF00, #0,255,0 light green
PROBABILITY_COLOR=   95,  100, 0X8B0000, #dark red

**Comment by vichdzgeo** [comment]
- [ ] Convertir el raster en binario (urbano no urbano) conservando el tamaño de la celda
- [ ] Del raster binario extraer los polígonos urbanos.

**Comment by vichdzgeo** [comment]
Script creado

Ruta: \CARPETAS_TRABAJO\vhernandez\codigo\curvanumerica\operacionesraster.py

**Comment by vichdzgeo** [comment]
## Serie VI de INEGI

Relación de las clasificaciones de las diferentes coberturas.
![image](https://user-images.githubusercontent.com/38017509/44866984-50546400-ac4c-11e8-9f76-86a2a619639f.png)

**Comment by vichdzgeo** [comment]
Script ubicado en: 

C:\Dropbox (LANCIS)\SIG\desarrollo\megadapt\procesamiento\curva_numerica\urb_a_curvan_v3.py
