### ISSUE TITLE
crear un shpefile a partir de los resultados de las escorrentías: las entidades geográficas deben ser las cuencas swat y las columnas serán la serie de tiempo para la que se corrió el modelo en intervalos anuales  

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#56]

**Comment by serranoycandela** [comment]
Pensar con Luis y Yosune esta parte porque dado que el modelo de escorrentía corre diario no sería dificil que el resultado fuera escorrentía por semana, sobre todo si Yosune y yo logramos generar la serie de tiempo a partir de los datos en los modelos de cambio climático

**Comment by vichdzgeo** [comment]
## Generación de una capa que contenga el ID de la subcuenca y el número de la banda de elevación inferior.

La capa fue generada, se localiza en dropbox:

CARPETAS_TRABAJO\vhernandez\megadapt\escorrentia\swat_EB_low.shp

**Comment by serranoycandela** [comment]
estos son los intervalos anuales

2007 5114-5480
2008 5479-5844
2009 5845-6209
2010 6210-6574
2011 6575-6939
2012 6940-7305
2013 7306-7670

**Comment by yosunemiquela** [comment]
supongo que 2007 es 5114 a 5479 y 2008 5480 a 5844 cierto?

**Comment by serranoycandela** [comment]
2007 5114-5478
2008 5479-5844
2009 5845-6209
2010 6210-6574
2011 6575-6939
2012 6940-7305
2013 7306-7670

**Comment by serranoycandela** [comment]
2007
![esc2007](https://user-images.githubusercontent.com/12860576/44599886-4ee2f180-a79d-11e8-843b-baff849f508f.png)



2008
![esc2008](https://user-images.githubusercontent.com/12860576/44599899-586c5980-a79d-11e8-861a-d4cc2b48be0e.png)


2009
![esc2009](https://user-images.githubusercontent.com/12860576/44599912-6326ee80-a79d-11e8-83c9-cface97a262a.png)


2010
![esc2010](https://user-images.githubusercontent.com/12860576/44599923-6ae69300-a79d-11e8-96d5-677a3b37dda8.png)


2011
![esc2011](https://user-images.githubusercontent.com/12860576/44599937-72a63780-a79d-11e8-92c0-84a7b77423bc.png)


2012
![esc2012](https://user-images.githubusercontent.com/12860576/44599948-7afe7280-a79d-11e8-96ed-2e47ebf24870.png)


2013
![esc2013](https://user-images.githubusercontent.com/12860576/44599966-85b90780-a79d-11e8-9c30-502e09970e4c.png)

**Comment by yosunemiquela** [comment]
el shape de escorrentías anuales por cuenca está en:
CARPETAS_TRABAJO/ymiquelajauregui/Escorrentia

**Comment by yosunemiquela** [comment]
El .csv con las escorrentías anuales se encuentra en:

MEGADAPT/mega_procesamiento/input_modelos/balance_hidrico_swat_/Outputs

**Comment by yosunemiquela** [comment]
Equivocación de ruta anterior..
corrección:
El .csv con las escorrentías anuales se encuentra en:
MEGADAPT/mega_procesamiento/output_modelos/balance_hidrico/Outputs
