### ISSUE TITLE
calcular los números de curva para cada año de cada escenario de crecimiento urbano

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#57]

**Comment by vichdzgeo** [comment]
para cada escenario se proceso datos anuales del 2016 hasta el 2060. existe una capa por año llamada swat_master_aaaa.shp. estas capas se encuentran dentro de la carpeta de salida de cada escenario. por ejemplo: 
\SIG\desarrollo\megadapt\procesamiento\urbanizacion\escenarios\e04_s6_flores_v2_airport_no11\salida\swat_master_urban_2016.shp

ruta: \SIG\desarrollo\megadapt\procesamiento\urbanizacion\escenarios\
- e04_s6_flores_v2_airport_no11
- e04_s6_flores_v2_airport_no11_excl_0
- e04_s6_flores_v2_airport_no11_excl_total
- e04_s6_flores_v2_noairport_no11
- e04_s6_flores_v2_noairport_no11_excl_0

**Comment by vichdzgeo** [comment]
@yosunemiquela
