### ISSUE TITLE
Generar las series de tiempo de evapotranspiración y precipitación para cada escenario de urbanización

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#60]

**Comment by yosunemiquela** [comment]
No entiendo el issue. Cada escenario de urbanización? Cuáles específicamente?
Lo discutimos? @serranoycandela

**Comment by yosunemiquela** [comment]
Se cambió el título para darle más sentido a la tarea.
Se cuentan con los promedios mensuales de precipitación y temperatura proyectados para los escenarios IPCC RCP 4.5 y 8.5 para los dos periodos: near future y far future. La tarea implica generar series de tiempo de clima proyectado utilizando estos promedios. Se identificaron dos paquetes en R con potencial para resolver dicha tarea: Rglimclim y RMAWGEN. Después de una exploración general de estos dos paquetes, se decidió utilizar el primero ya que es capaz de incluir autocorrelaciones (espaciales y temporales).
Nos hemos familiarizado con la estructura del paquete, los datos que los alimentan y el tipo de output que generará. se han identificado tres tareas a corto plazo:
 1. Entender el formato geográfico
 2. Entender cómo alimentar a la función de generación de datos con las medias de clima proyectadas. Para resolver esto, se utilizarán dos artículos que utilizan Rglimclim para generar series de tiempo futuras. 
 a) https://elvisasong.com/wp-content/uploads/2018/04/JP3.pdf
 b) https://link.springer.com/article/10.1007%2Fs00382-016-3004-z

**Comment by yosunemiquela** [comment]
El script del ejercicio así como los datos de prueba se encuentran en: 
SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/climate_pojections

**Comment by yosunemiquela** [comment]
c) Encontrar la combinación de parámetros iniciales de ajuste del modelo GLM
