### ISSUE TITLE
Crear una capa de centralidad en la red de drenaje por ageb

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#62]

**Comment by serranoycandela** [comment]
@JosueMA @aleestrada @iaga @AlfMedina 
Se creo la capa de centralidad que es el número de tramos que drenan hacia cada ageb, para el cálculo se utilizó la red de drenaje en lluvias editada por Edith
/Dropbox/SIG/desarrollo/sig_megadapt/procesamiento/drenaje_primario/red_lluvias_cg.json 
 y el script 
/Dropbox/SIG/desarrollo/sig_megadapt/procesamiento/centralidad_drenaje/centralidad.py

y el resultado está en: /Dropbox/SIG/desarrollo/sig_megadapt/procesamiento/centralidad_drenaje/agebs_centralidad.shp
![screen shot 2018-12-03 at 12 54 43 pm](https://user-images.githubusercontent.com/12860576/49395334-cceb5880-f6fb-11e8-8366-d40001566e09.png)
<img width="162" alt="screen shot 2018-12-03 at 12 54 00 pm" src="https://user-images.githubusercontent.com/12860576/49395345-d1177600-f6fb-11e8-9959-70b3ea7c2bfd.png">

**Comment by iaga** [comment]
@serranoycandela ¿Podrías indicarme por favor cuáles son las unidades o qué representa el mapa?

**Comment by serranoycandela** [comment]
@iaga
es como dice la descripción: número de tramos del drenaje 
es decir, la cantidad de tramos que drenan a cada ageb, no está normalizado ni nada, es solo la cuenta de tubos cuyo drenaje se acumula en cada ageb

**Comment by serranoycandela** [comment]
el archivo /Dropbox/SIG/desarrollo/sig_megadapt/procesamiento/centralidad_drenaje/agebs_centralidad.json
contiene dos campos de interés:
n_tramos: es el numero de tramos de drenaje que drena hacia cada ageb
tribu: es la lista de los ids de los tramos de la red que drenan hacia cada ageb

n_tramos es la cantidad que usaremos como medida de la centralidad en la red de drenaje
