### ISSUE TITLE
Desarrollar el método para a partir de la escasez disparar el double coupling

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#63]

**Comment by iaga** [comment]
Los datos del modelo de protestas que generó @aleestrada se encuentran en la ruta: \CARPETAS_TRABAJO\aestrada\Entrega\protestas

**Comment by iaga** [comment]
# Explorar el módulo de python para ANP

Nombre de la biblioteca: pyanp

Documentación: https://pyanp.readthedocs.io/en/latest/refs/limitmatrix.html

1.- Para instalar la biblioteca es necesario revisar la página www.pyanp.org

2.- Con el objetivo de revisar el funcionamiento del paquete, se corrieron los
siguientes ejemplos (tomados de la página de la biblioteca ):

- Prioridades a partir de la matriz de comparaciones pariadas
- Valor propio
- Inconsistencia
- Para la matriz límite:
  - Calcular la matriz y extraer las prioridades
  - Normalizar

Archivo en python: CARPETAS_TRABAJO\igrave\avance_personal\anp_example.py

**Comment by iaga** [comment]
# Revisar los pesos de la supermatriz

El modelo mental, para la subred **escasez**, contiene los siguientes nodos:

![imagen](https://user-images.githubusercontent.com/41757755/49967811-8fe84880-fee9-11e8-9b1b-0f571f25e64e.png)

Los nodos más relevantes (y sus respectivos criterios) para este caso:


* **Riesgos_población**: Riesgos por daños a la infraestructura hidráulica que afectan a la población
   * Escasez de agua: Cantidad de agua insuficiente para las necesidades diarias (derecho humano) (por volumen o horas de entrega) 

* **Socio-institucional**: Criterios socio-institucionales, presiones sociales, demandas y peticiones que recibe SACMEX
   * Abastecimiento: Necesidad de la población en cuanto a servicios hidráulicos (agua potable, drenaje)
   * Petición de Delegaciones: Solicitud de servicios e infraestructura hidráulica o nuevas conexiones al sistema hidráulico por Delegaciones
   * Presión de medios: Presión de los medios de comunicación
   * Presión social: Percepción del descontento social directa de la población e indirecta a través agencias de gobierno, quejas, comentarios recibidos por redes sociales y teléfono
