### ISSUE TITLE
crear capas geográficas de encharcamientos 2015-2017 por ageb a partir de los datos de sacmex

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#68]

**Comment by iaga** [comment]
Procedimiento:

1. Localización y asignación del valor mínimo asignado a los encharcamientos 2007-2014 sin registro (issue #989-planeación). El valor mínimo encontrado:

TIRANTE | LARGO | ANCHO
-- | -- | --
0.05 | 0.5 | 0.5

2. Localización del umbral de corte (2007-2014) entre encharcamientos/inundaciones: 208.5mm^3
3. Generación de las bases de datos asociadas: freq_ench_1517.csv y freq_in_1517.csv
Ruta: SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\frecuencia_ench_inunda1517

**Comment by iaga** [comment]
El archivo markdown que contiene el procedimiento: frec_ench_in_15_17.Rmd

Ruta: SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\frecuencia_ench_inunda1517

**Comment by aleestrada** [comment]
Desapareció la ruta en la que se encuentran los datos 
*(\SIG\desarrollo\megadapt\procesamiento\encharcamientos_2015_2017\insumos\bd_megadapt_ench_15_17_colid_v2.csv)* 
que sirven como insumos de las capas. La ruta en la que se solicitó colocar los datos se encuentra en el issue  planeacion-colaborativa #963. 
La base de datos fue utilizada en el issue planeacion-colaborativa #959 y al parecer ahí se modificó su ruta.
@edithvilla  ¿nos puedes indicar dónde se encuentran los datos por favor?

**Comment by edithvilla** [comment]
@aleestrada  Ya está reparada la carpeta
![dropbox](https://user-images.githubusercontent.com/25182051/47034061-e892a380-d13b-11e8-9fc3-86ac9d7e1517.PNG)

![dropbox2](https://user-images.githubusercontent.com/25182051/47034070-ef211b00-d13b-11e8-9a55-58e15233e611.PNG)
