### ISSUE TITLE
Generar capas anuales de precipitación a nivel de AGEB 2000 - 2017

### ISSUE THREAD

**Issue by vichdzgeo** [sostenibilidad-unam/SHV#69]
- [x] Solicitar los datos proporcionados historicos al responsable de activos.
- [x] Depurar la base de datos.
- [x] Generar la interpolación
- [x] Escalar los datos a nivel de AGEB

**Comment by vichdzgeo** [comment]
## Procesar los datos proporcionados por SACMEX
ruta de los datos: MEGADAPT\mega_insumos\agosto2016\SACMEX\INFORMACION DE LLUVIAS\ALTURAS DE PRECIP DIARIAS Y MENSUAL

ruta de trabajo: C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\precipitacion_00_14

- Se extraen los datos acumulados de precipitación de los años 2000 al 2014,
- Del archivo UBICACIONESTA.xls se extrae la latitud y longitud de las estaciones.
- Se genera un archivo est_prec_acum_00_13.xls el cúal contiene

**Comment by vichdzgeo** [comment]
@yosunemiquela @iaga @aleestrada @serranoycandela

**Comment by vichdzgeo** [comment]
@yosunemiquela  
se procesan los datos conforme a tu solictud. 
ruta:
\SIG\desarrollo\sig_megadapt\entregables\series_tiempo

series de tiempo listas:
- prec_st_1950_2013.csv

**Comment by vichdzgeo** [comment]
## Generación de capa de precipitación para los años 2000 - 2016
ruta: C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\entregables\precipitacion_ageb\prec_00_16.shp


Se unieron las capas anuales de precipitación en una sola, los nombres de los campos p_aaaa donde "aaaa" representa la precipitación acumulada anual.

Se crea un campo del promedio de los datos.

@iaga  @aleestrada @AlfMedina

**Comment by vichdzgeo** [comment]
Se actualiza la capa incorporando el año 2017

ruta: SIG\desarrollo\sig_megadapt\entregables\precipitacion_ageb\prec_00_17.shp

Se unieron las capas anuales de precipitación en una sola, los nombres de los campos p_aaaa donde "aaaa" representa la precipitación acumulada anual.

Se actualiza el campo del promedio de los datos.

**Comment by vichdzgeo** [comment]
## Generar una capa de precipitación anual multiplicado por el área del ageb

la capa generada se encuentra en la siguiente ruta: 
C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\entregables\prec_volumen\prec_vol_ageb.shp

se creo con el siguiente código: 

~~~
import qgis
from qgis.core import *
from qgis.analysis import *
from os.path import join
from PyQt4.QtCore import *
from osgeo import gdal, ogr,osr
import math
from datetime import datetime, date, time, timedelta


def v_copia(path_vector,path_salida):
    """
    Crea una copia de la capa a partir de la ruta de la capa, la capa es creada con el mismo sistema de
    referencia que el origen.
    """
    vlayer = QgsVectorLayer(path_vector,"","ogr")
    clonarv = QgsVectorFileWriter.writeAsVectorFormat(vlayer,path_salida,'utf-8',vlayer.crs(),"ESRI Shapefile")



def crear_campo(path_vector,nombre_campo,tipo):

    ''' Crear_campo(path_vector,nombre_campo,tipo)
    Esta funcion crea un campo segun el tipo especificado.
    path_vector:La ruta del archivo shapefile al cual se le quiere agregar el campo
    nombre_campo: Nombre del campo nuevo
    tipo: es el tipo de campo que se quiere crear:
    Int: para crear un campo tipo entero
    Double: para crear un campo tipo doble o flotante
    String: para crear un campo tipo texto
    Date: para crear un campo tipo fecha '''

    if len(nombre_campo) >10:
        print("el nombre del campo debe contener maximo 10 caracteres")
    else:
        if tipo == "Int":
            nombre=QgsVectorLayer(path_vector,"","ogr")
            nombre.dataProvider().addAttributes([QgsField(nombre_campo.lower(),QVariant.Int)])
            return nombre
        elif tipo == "Double":
            nombre=QgsVectorLayer(path_vector,"","ogr")
            nombre.dataProvider().addAttributes([QgsField(nombre_campo.lower(),QVariant.Double)])
            return nombre
        elif tipo == "String":
            nombre=QgsVectorLayer(path_vector,"","ogr")
            nombre.dataProvider().addAttributes([QgsField(nombre_campo.lower(),QVariant.String)])
            return nombre
        elif tipo == "Date":
            nombre=QgsVectorLayer(path_vector,"","ogr")
            nombre.dataProvider().addAttributes([QgsField(nombre_campo.lower(),QVariant.Date)])
            return nombre
        else:
            print ("el tipo no existe o hay error en su declaracion")

sig_path="C:/Dropbox (LANCIS)/SIG/desarrollo/sig_megadapt/procesamiento/prec_volumen/"
precipitacion = QgsVectorLayer (sig_path+"insumos/ageb_prec_00_17_utm.shp","","ogr")

v_copia(sig_path+"insumos/ageb_prec_00_17_utm.shp"  , sig_path+"salida/ageb_vol_prec_utm.shp")

vol_prec = QgsVectorLayer (sig_path+"salida/ageb_vol_prec_utm.shp","","ogr")

campos=[field.name() for field in precipitacion.fields()] [1:]

for campo in campos:
    if campo !='area':
        print campo
        campo_v=campo+'v'
        crear_campo(sig_path+"salida/ageb_vol_prec_utm.shp",campo_v,"Double")
        
        vol_prec.startEditing()
        for ageb in vol_prec.getFeatures():
            volumen = (ageb[campo]*ageb['area'])/1000
            ageb[campo_v]=volumen
            vol_prec.updateFeature(ageb)
            #print "el ageb ",ageb['ageb_id'],"para el anio",campo, "tiene un volumen de " , volumen, "dato del shape",ageb[campo]
        vol_prec.commitChanges()
        
print "el proceso se termino"
     
~~~

**Comment by iaga** [comment]
Los insumos para la precipitación por volumen (modelo de encharcamientos/inundaciones) se encuentran ubicados en la ruta:

\SIG\desarrollo\sig_megadapt\entregables\prec_volumen\prec_vol_ageb.shp

@yosunemiquela

**Comment by iaga** [comment]
Los insumos para la precipitación por volumen (modelo de encharcamientos/inundaciones) se encuentran ubicados en la ruta:

\SIG\desarrollo\sig_megadapt\procesamiento\prec_volumen\prec_vol_ageb.shp

@yosunemiquela

**Comment by iaga** [comment]
Los insumos para la precipitación por volumen (modelo de encharcamientos/inundaciones) se encuentran ubicados en la ruta:

\SIG\desarrollo\sig_megadapt\procesamiento\modelo_ench_inund\insumos\vol_prec\ageb_vol_prec_utm

@yosunemiquela
