### ISSUE TITLE
Ubicar datos de tiempo de respuesta de sacmex ante fugas y faltas

### ISSUE THREAD

**Issue by iaga** [sostenibilidad-unam/SHV#73]
Localizar los archivos que contienen la información de tiempo de respuesta de sacmex para fugas y faltas e indicar el año

**Comment by iaga** [comment]
@abaezacastro Ya estamos en proceso de localizar los datos, hoy mismo te indicamos la ruta y te damos acceso

**Comment by aleestrada** [comment]
Se colocó en la carpeta: fugas_faltas_2017, la capa de días promedio sin agua por AGEB para el 2017 (faltas) y las fugas por AGEB.

Los datos se encuentran en la siguiente ubicación:

MEGADAPT\mega_procesamiento\input_modelos\modelo_escasez\datos\fugas_faltas_2017
