### ISSUE TITLE
refinar la red de drenaje

### ISSUE THREAD

**Issue by serranoycandela** [sostenibilidad-unam/SHV#74]
usando esta aplicación web:
http://patung.mine.nu/~fidel/tributarias/tramos_tributarios.html

un ejemplo de como usar este link, aquí el problema es con el tramo 64, osea "EDGE_NUM" = 64:
![screen shot 2018-10-30 at 5 13 50 pm](https://user-images.githubusercontent.com/12860576/47757338-82de0580-dc6b-11e8-99b8-c93d5e46c101.png)

toda esa rama termina ahí y no se conecta con nada:
![screen shot 2018-10-30 at 5 36 50 pm](https://user-images.githubusercontent.com/12860576/47757343-8b364080-dc6b-11e8-876d-48981e3260e1.png)

**Comment by serranoycandela** [comment]
otro ejemplo:
![screen shot 2018-10-30 at 10 11 21 pm](https://user-images.githubusercontent.com/12860576/47765726-f47c7a80-dc90-11e8-97c7-fc3609088e4f.png)
también toda esa rama ya no se conecta con nada:
![screen shot 2018-10-30 at 10 12 09 pm](https://user-images.githubusercontent.com/12860576/47765749-137b0c80-dc91-11e8-9031-012a8f70b6f9.png)

**Comment by edithvilla** [comment]
@serranoycandela es necesario que me indiques:
1. Qué archivo es el que tengo que corregir?
2. Qué procedimiento voy a seguir para hacer las correcciones?

**Comment by edithvilla** [comment]
La indicación de @serranoycandela es hacer una tabla descriptiva con los siguientes campos:

ID | Problema | Solución

ejemplo: 
ID | Problema | Solución
64 | no se conecta | se necesita conectar con el ID 1285

**Comment by edithvilla** [comment]
De acuerdo a la reunión del día de hoy (14 de noviembre) se van hacer las correcciones sobre la red. Con la herramienta de edición vectorial en QGIS.
Ruta de trabajo
\SIG\desarrollo\sig_megadapt\procesamiento\drenaje_primario

**Comment by edithvilla** [comment]
Avances en la corrección de la red primaria por delegación

1 - [x] Cuajimalpa
2. - [ ] Álvaro Obregón
3. - [ ] La Magdalena Contreras

**Comment by edithvilla** [comment]
### DUDAS PARA SACMEX

El Interceptor Poniente II cuándo entra en operación? y qué drenaje va a conectar? solo conecta el vaso regulador del Cristo? Cómo se conecta el Interceptor Poniente? a través del Río Ondo --- Vaso Regulador del Cristo --- Interceptor Poniente II

**Comment by edithvilla** [comment]
@serranoycandela ya está terminado la alcaldía Gustavo A. Madero. Por favor puedes actualizar la aplicación para autoverificar.

Solo falta corregir  el Interceptro Centro-Poniente

**Comment by edithvilla** [comment]
### Aplicación web
En QGIS
1. La capa red_lluvias.shp se guarda como GeoJSON y en coordenadas geográficas (EPSG: 4326)
2. A la capa GeoJSON se le agregan tres columnas:
   - tribu  (string, 5000, contenido null)
   - tributan    (string, 200, contenido null)
   - n_tramos    (entero64bits, 10, contenido null)

Guardar cambios

En explorador de windows
3. Sobre el archivo se edita la extensión de geojson a **.json**

4. Hice una copia del script de tramos_tributarios.py en la carpeta de trabajo y corregí el path de la línea 6

**Comment by edithvilla** [comment]
@vichdzgeo insumos para hacer script para actualizar en la capa de red_lluvias las coordenadas de los nodos

path: C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\drenaje_primario

- insumos:
red_lluvias.shp
nodos_lluvias_v2.shp

**Comment by edithvilla** [comment]
El script para obtener las coordenadas de la capa de nodos_lluvias.shp y rellenar las columnas de la capa de red_lluvias.shp está en C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\drenaje_primario\tramos_coord_nodos.py

**Comment by edithvilla** [comment]
@serranoycandela por favor podrías actualizar la plataforma de la red primaria, el archivo JSON está en: 
\SIG\desarrollo\sig_megadapt\procesamiento\drenaje_primario\red_lluvias_cg.json

también ya están listo los shapes para el siguiente proceso:
nodos_lluvias.shp
red_lluvias.shp

**Comment by edithvilla** [comment]
@vichdzgeo ya están las capas finales con sus markdown en:

\SIG\desarrollo\sig_megadapt\entregables\drenaje_primario\

**Comment by edithvilla** [comment]
### Calculo de capacidad de desalojo, ecuación de Manning (Q50 y Q100)

1. Sobre la capa de red_lluvias se calculará la Q50 y Q100

2. Crear el Json de la red de lluvias y agregarle los campos: tribu, tributan y n_tramos

3. Entrega del shape con los siguientes atributos: edge_num, q50, q100 y n_tramos

**Comment by edithvilla** [comment]
esta es la nueva liga para revisar la red de desalojo

http://patung.mine.nu/~evilla/tributarias/tramos_tributarios.html

**Comment by edithvilla** [comment]
@serranoycandela 
ya está el cálculo de la Q100 y Q50 para lluvias:
\SIG\desarrollo\sig_megadapt\entregables\drenaje_primario\capacidad_red_lluvias.shp

también ya le agregué las columnas tribu, tributan y n_tramos
\SIG\desarrollo\sig_megadapt\entregables\drenaje_primario\capacidad_red_lluvias_cg.json

**Comment by edithvilla** [comment]
@serranoycandela 
### Productos del cálculo de capacidad de desalojo

- **cap_red_lluvias_cg.json**      (capacidad de desalojo por edge, también tiene las columnas de tribu, tributan y n_tramos)
RUTA: \SIG\desarrollo\sig_megadapt\procesamiento\drenaje_primario

- **capacidad_red_lluvias.shp**      ( tiene el cálculo de la capacidad Q100 Y Q150)
RUTA: \SIG\desarrollo\sig_megadapt\procesamiento\drenaje_primario

- **capacidad_drenaje.xlsx**          (es el cálculo de la capacidad de drenaje para lluvias y secas Q100 Y Q50)
RUTA: \SIG\desarrollo\sig_megadapt\procesamiento\drenaje_primario\bd

**Comment by serranoycandela** [comment]
@iaga @aleestrada @edithvilla 
se creó la capa de capacidad por ageb con base en la red de desalojo tomando el campo q100 que calculó Edith entiendo que el campo q100 de la red de drenaje fue calculada con la ecuación de manning y sus unidades son metros cúbicos por segundo, resalta el canal nacional que tiene una q100 de mas de 900 metros cúbicos por segundo @edithvilla hay que verificar que es correcto.

![screen shot 2018-12-03 at 11 20 40 pm](https://user-images.githubusercontent.com/12860576/49420948-642fca80-f753-11e8-8f49-378b4fc2769d.png)
<img width="156" alt="screen shot 2018-12-03 at 11 20 11 pm" src="https://user-images.githubusercontent.com/12860576/49420952-685be800-f753-11e8-8f73-521702ddf4f8.png">

esta capa se generó con el script:
\SIG\desarrollo\sig_megadapt\procesamiento\capacidad\calcula_capacidad2.py

y el resultado es la capa:
\SIG\desarrollo\sig_megadapt\procesamiento\capacidad\agebs_capacidad.shp

las unidades son las mismas que las de q100 de la red de drenaje, o sea metros cúbicos por segundo

**Comment by edithvilla** [comment]
4 de diciembre, 2018
### Reunión con el equipo de MEGADAPT

1. Se discutió sobre la red de lluvia y secas
2. Ya no se puede retrasar el modelo, se tiene que correr el modelo en el cluster
3. Se tienen listas las capas de centralidad, capacidad Q50 y Q100 precipitación
4. Hay dos equipo: para correr los dos modelos (panel y frecuentista)
5. El día de hoy se tienen los resultados de los dos modelos. Si hoy no salen los resultados los modelos se hará de una manera más sencilla y se calcula tres días más. 
6. Si se tienen los resultados del modelo, los resultados se le mandan a Andrés para que lo incorpore al modelo, la incorporación de los resultados al modelo debe tardar un día.
7. Reglas de decisión (autómata celular) para el análisis de encharcamiento
8. Si no hay un modelo estadístico que se ajuste, se utilizan los datos "observados",  (base de datos de los reportes de encharcamiento)  y con lógica se construye el modelo. Promedio anual por año. Algo que diga las características de las agebs. Se necesita hacer un PCA para ver como se distribuyen las características.

### El modelo basado en reglas
El producto: es una matriz de ageb (filas) por las variables (columnas)
Se necesita trabajar en las reglas, ejemplo: si la ageb pertenece al grupo 1 y es seleccionada para hacer algo se cambia de grupo.

Se va a probar en "R" el modelo lógico

PCA: se meten todas las variables y que salgan los grupos que tengan que salir

Se realizarán 2 PCA: uno para inundaciones y otro para encharcamientos

**Comment by edithvilla** [comment]
### Canal Nacional @serranoycandela 

El Canal Nacional tiene una longitud aproximada de 8 km, de los cuales 5.2 corren en el límite oriente de la Delegación Coyoacán; ancho en la parte superior de 12 m y 4 m en el fondo, sus taludes son de 1.1, posee una pendiente casi nula y su sentido de escurrimiento es de sur a norte. El canal se encarga de regular las avenidas provenientes del río San Buenaventura y desalojar las aguas pluviales y residuales de la parte oriente de la Delegación Coyoacán, a través de tres plantas de bombeo localizadas en la margen izquierda del mismo cauce, en la salida de los principales colectores. Además recibe las aportaciones del canal de Chalco, a la altura de calzada de la Virgen, por medio de la planta de bombeo Canal Nacional - Canal de Chalco.

Fuente: Plan Hidráulico Delegacional 2010-2015 - Delegación de Coyoacán
\MEGADAPT\mega_insumos\agosto2016\SACMEX\16 PLANES HIDRAHULICOS DELEGACIONALES COMPLETOS\3.-COYOACÁN
Imágenes del Canal
http://www.paot.mx/micrositios/canal-nacional/
http://www.paot.org.mx/transparencia/2014/segundo_trimestre/art_15/Fracc_X/SPA/Anexo/canal.pdf

**Comment by edithvilla** [comment]
@serranoycandela por favor necesito que revises la descripción de los atributos para los metadatos

1. tribu: la lista de trazos (tubos) que hacen llegar el desalojo de sus agua a ese trazo
2. tributan: la lista de trazos (tubos) contiguos que le hacen llegar el desalojo de sus aguas
3. n_tramos: número de trazos (tubos) que hacen llegar el desalojo de sus aguas a ese trazo

**Comment by edithvilla** [comment]
5 de diciembre
Se hizo una actualización de la red de lluvias. se conectó un tramo:
![captura1](https://user-images.githubusercontent.com/25182051/49545922-ab79a080-f8a4-11e8-81e6-f14d165ff5db.PNG)

![captura2](https://user-images.githubusercontent.com/25182051/49545990-da901200-f8a4-11e8-8f32-9c2afb0462f3.PNG)

**Comment by edithvilla** [comment]
@serranoycandela 
La red de lluvias, está revisada por quinta vez, corregida y actualizada.
La red está con base en los Planes Hidráulicos Delegacionales, yo diría que si se puede refinar con SACMEX estaría mejor, hay unos trazos que por falta de conocimientos pudiera ser que no están bien conectados, tal es el caso del Canal de Chalco que no estoy segura de si se conecta al Semiprofundo Canal Nacional-Canal de Chalco.
