### ISSUE TITLE
Explorar los datos de encharcamientos e inundaciones

### ISSUE THREAD

**Issue by aleestrada** [sostenibilidad-unam/SHV#75]
Dado que no es posible ajustar una regresión para inundaciones, se decidió hacer una revisión de los resultados existentes sobre inundaciones en la ciudad y analizar la base de datos original, para encontrar relaciones con otras variables y entender el fenómeno.

**Comment by aleestrada** [comment]
@iaga encontró el documento: file:///C:/Users/Alejandra%20Estrada/Downloads/SerieAzul_InstitutoIngenieria_UNAM.pdf
en el que se realizó un análisis de las inundaciones ante la fallas en el drenaje profundo en CDMX.

Se encontró lo siguiente:

- Definición de nivel mínimo de inundación: "Se considera inundación cuando la profundidad de la
capa de agua rebasa 20 cm, porque con ello es suficiente para afectar algunos de los contenidos de una casa. En general, con esta altura, se causan daños en casa habitación y obstrucciones en las vías de comunicación."
- La importancia del drenaje profundo en la generación de inundaciones.

**Comment by iaga** [comment]
@yosunemiquela @serranoycandela

**Comment by yosunemiquela** [comment]
Se volvieron a realizar los análisis para definir el umbral entre encharcamiento e inundación.
Se realizaró el siguiente procedimiento:
1. Se eliminaron todos los NA´s (53% del total de observaciones)
2. Se eliminaron todas las observaciones con un tirante mayor de 2 m (0.24%)
3. Se utilizaron dos umbrales. El primero definido por los ingenieron de SACMEX en función de la severidad (que tan profundo debe ser un cuerpo de gua para afectar las casas). este umbral corresponde a 0.2m de tirante. Se generaron .csv anuales utilizando este corte. Aproximadamente 59% son encharcamientos y  41% inundaciones.
4. Se definió el umbral utilizando la media del volumen+1 desviación estándar. El umbral corresponde a 200 m3.
5. Se corrió el modelo que evalúa el efceto de distintos sobre el coeficiente de variación entre las inundaciones y encharcamientos. De manera visual, se puede corroborar la información arrojada por el método descrito en el punto 4). Se incluye la siguiente imágen:
![image](https://user-images.githubusercontent.com/25304777/48221712-6bcca100-e358-11e8-886f-92767f95d784.png)
