### ISSUE TITLE
Definir el índice que refleje el comportamiento de drenaje ante las inundaciones y encharcamientos

### ISSUE THREAD

**Issue by edithvilla** [sostenibilidad-unam/SHV#77]
Ruta: 
/carpetas_trabajo/aestrada/megadapt/ench_inund_model/indice_drenaje

Insumos:
1. Alcantarillado (número de alcantarillas por ageb) \SIG\desarrollo\sig_megadapt\entregables\alcantarillado\alcantarillado_ageb.shp

2. Lumbreras (lumbreras por ageb) 
\SIG\desarrollo\sig_megadapt\entregables\drenaje_profundo\lumbreras_ageb.shp

3. Drenaje primario en secas (volumen neto por ageb) 
\SIG\desarrollo\sig_megadapt\entregables\volumen_drenaje_ageb\volumen_cdmx_ageb.shp
Revisar el archivo **volumen_cdmx_ageb.md** para ver el procedimiento
En esta misma carpeta se encuentra el script de python (volumen.py)

4. Plantas de bombeo y carcamos (la capa de carcamo se une a la capa de planta de bombeo para solo tener una)
\MEGADAPT\mega_insumos\agosto2016\SACMEX\SHAPES\INFRAESTRUCTURA HIDRAULICA DF_SACMEX_020915\DESALOJO\CARCAMO.shp     y      PLANTA_BOMBEO.shp

**Comment by edithvilla** [comment]
### Cálculo del índice de drenaje 

1. Modelo multicriterio AHP
META: Lista priorizada de AGEB en términos de suceptibilidad a inundaciones y encharcamientos
/carpetas_trabajo/aestrada/megadapt/ench_inund_model/indice_drenaje

**Comment by aleestrada** [comment]
##

**Comment by iaga** [comment]
# Exploración de los mapas de la infraestructura del drenaje por ageb

## Alcantarillado

![alcantarillado_ageb](https://user-images.githubusercontent.com/41757755/48218818-5d7a8700-e350-11e8-8152-a0f01b7996f0.png)

## Bombeo

![bombeo_ageb](https://user-images.githubusercontent.com/41757755/48218875-8ac73500-e350-11e8-948e-50d242d188cb.png)

## Lumbreras

![lumbreras_ageb](https://user-images.githubusercontent.com/41757755/48218890-97e42400-e350-11e8-9ffa-482177ef3398.png)

**Comment by edithvilla** [comment]
### Drenaje primario secas

El drenaje primario en secas consta de la red primaria (tubos con diámetros en 61 cm y 315 cm) y red secundaria (tubos con diámetro < 61 cm).
Esta red también cuenta con un cauce a cielo abierto: 

Canal Nacional. El canal Nacional se localiza al sureste del Distrito Federal y da inicio en la Delegación Xochimilco; en su recorrido recibe las descargas del río San Buenaventura y canal de Chalco para alimentar al río Churubusco, por medio de la planta de bombeo Miramontes.
Este dren cuenta con una longitud aproximada de 8.0 km, de los cuales 5.2 corren en el límite oriente de la Delegación de Coyoacán; ancho en la parte superior de 12 m y 4 m en el fondo. fuente: Plan Hidráulico de la Delegación Coyoacán (MEGADAPT\mega_insumos\agosto2016\SACMEX\16 PLANES HIDRAHULICOS DELEGACIONALES COMPLETOS\3.-COYOACÁN\INFORME.pdf)

**Comment by edithvilla** [comment]
@aleestrada de acuerdo a la reunión del día lunes 12 con Luis, cuáles serían mis actividades o los acuerdos en los que estoy involucrada?

**Comment by aleestrada** [comment]
@edithvilla De acuerdo con la reunión con Luis se tienen que realizar las siguientes actividades para definir el índice:
 - Son necesarios los nuevos datos de capacidad de drenaje con los datos de pendiente constantes.
- Es necesario definir de qué forma interactúan las lumbreras con el drenaje
- Se requiere realizar un nuevo ejercicio de AHP en el que no se involucren los criterios naturales, además se comentó que el peso de la capacidad debería ser mayor a 40, para que tuviera sentido. Se propone que @serranoycandela esté presente en el ejercicio. 

@edithvilla tú estás involucrada en todos los puntos.

**Comment by edithvilla** [comment]
Información
http://www.ptolomeo.unam.mx:8080/xmlui/bitstream/handle/132.248.52.100/12056/Tesis.pdf?sequence=1

Tesis de maestría: Impacto Ambiental del manejo de los sedimentos extraídos de redes de alcantarillado urbano

Habla sobre los sedimentos que se encuentran en la red de drenaje, una de las causas de los encharcamientos en la ciudad

**Comment by edithvilla** [comment]
De acuerdo a la reunión que se tuvo con Luis el día 4 de diciembre #1011[](https://github.com/lancis-apc/planeacion-colaborativa/issues/1011) Planeación Colaborativa, ya no se va a seguir este camino, ya que se decidió ocupar la capa de lluvias
