### ISSUE TITLE
Generar la base de datos para encharcamientos e inundaciones (2007-2017)

### ISSUE THREAD

**Issue by iaga** [sostenibilidad-unam/SHV#78]
A partir de la reunión con Luis del 07/11/2018 y de la exploración de los datos de encharcamientos e inundaciones (issue #75), se decidió:

- Eliminar outliers 
- Eliminar NA
- Estimar un nuevo corte de encharcamientos e inundaciones

Dado que no fue posible recuperar la base de datos original sin imputaciones, fue necesario trabajar con la base de datos limpia para los años 2007-2017.

FYI @edithvilla y @serranoycandela

**Comment by iaga** [comment]
# Descripción del proceso de generación de la base de datos

## Depuración de la base de datos original y asignación del COL_ID

A partir de los reportes proporcionados para los años 2007-2009 (MEGADAPT/mega_insumos/agosto2016/SACMEX/BASE DE DATOS/HISTORICO ENCHARCAMIENTOS/ENCHARCAMIENTOS 2007 A 2014.csv) y 2009-2017 (\SIG\desarrollo\sig_megadapt\procesamiento\basura\insumos\ENCHARCAMIENTOS 2009 al 2017.csv) se generó la base de datos **bd_depurada_encharcamientos_0717.csv** que contiene, principalmente, los campos de interés: MUNICOLO, COL_ID, TIRANTE, LARGO y ANCHO

Para depurar la base, fue necesario:

- Agregar al diccionario de Python palabras con errores ortográficos
- Asignar un col_id (de los existentes en la base que contiene municolo) a las colonias con inundaciones grandes y que no era posible identificarlas por no tener una asignación
- Seleccionar un corte de similitud (aprox. 0.78) entre las cadenas de texto 

Los detalles se encuentran en el script:**extraccion_encharcamientos_0717.Rmd**

Ruta: SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\ench_inun_0717

## Estimación del nuevo corte de encharcamientos e inundaciones

Responsable: @yosunemiquela 

Se volvieron a realizar los análisis para definir el umbral entre encharcamiento e inundación.
Se realizaron los siguientes procedimientos:
1. Se eliminaron todos los NA´s (53% del total de observaciones)
2. Se eliminaron todas las observaciones con un tirante mayor de 2 m (0.24%)
3. Se utilizaron dos umbrales. El primero definido por los ingenieros en función de la severidad (qué tan profundo debe ser un cuerpo de agua para afectar las casas). Este umbral corresponde a 0.2m de tirante. Se generaron .csv anuales utilizando este corte. Aproximadamente 59% son encharcamientos y  41% inundaciones.
4. Se definió el umbral utilizando la media del volumen+1 desviación estándar. El umbral corresponde a 200 m3.
5. Se corrió el modelo que evalúa el efecto de distintos umbrales o cortes sobre el coeficiente de variación entre las inundaciones y encharcamientos. De manera visual, se puede corroborar la información arrojada por el método descrito en el punto 4). Se incluye la siguiente imagen que ilustra el cambio en el coeficiente de variación y las distintas proporciones entre lo que se considera encharcamiento e inundación bajo distintos umbrales (m3):
![image](https://user-images.githubusercontent.com/25304777/48221712-6bcca100-e358-11e8-886f-92767f95d784.png)
6. Se volvieron a generar .csv anuales con dichos cortes.
7. Los .csvs se encuentran en la siguiente ruta:
Tirante: SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/ench_inun_0917/Threshold_tirante
Volumen: SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/ench_inun_0917Threshold_volumen
El markdown con todos los procedimientos se encuentra en: 
CARPETAS_TRABAJO/ymiquelajauregui/megadapt/Inundaciones/encharcamientos_inundacion

## Asignación de un col_id único para cada reporte

Objetivo: Reducir el número de reportes a un col_id único por colonia (existen varios reportes para la misma colonia y es necesario tener un registro único por col_id para poder generar las capas correspondientes) para cada uno de los cortes (tirante y volumen).

Los insumos  (Threshold_volumen/Threshold_tirante) se encuentran ubicados en las rutas:

Tirante: SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/ench_inun_0917/Threshold_tirante
Volumen: SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/ench_inun_0917Threshold_volumen

Y los respectivos scripts:
- col_id_unicos_volumen.Rmd
- col_id_unicos_tirante.Rmd

Ruta: SIG/desarrollo/sig_megadapt/procesamiento/encharcamientos_escorrentias/ench_inun_0917/

Los archivos de salida se encuentran ubicados en la ruta:

\SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\ench_inun_0917\col_id_unico

Dentro de las carpetas:

- col_id_unico_tirante
- col_id_unico_volumen

### Corte Volumen

#### Frecuencia de encharcamientos.
Archivo de salida: **f_en_v.csv**
La base de datos contiene los siguientes campos:

COL_ID | f_en_v07 | f_en_v08 | f_en_v09 | f_en_v10 | f_en_v11 | f_en_v12 | f_en_v13 | f_en_v14 | f_en_v15 | f_en_v16 | f_en_v17 | pf_en_v
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**f_en_vXX**. La frecuencia de encharcamientos (corte volumen): Suma de los eventos de encharcamientos para el año XX.
**pf_en_v**. Promedio de la frecuencia de encharcamientos (corte volumen). Promedio de la frecuencia de encharcamientos para todos los años (2007-2017).

#### Frecuencia de inundaciones.
Archivo de salida: **f_in_v.csv**

La base de datos contiene los siguientes campos:

COL_ID | f_in_v07 | f_in_v08 | f_in_v09 | f_in_v10 | f_in_v11 | f_in_v12 | f_in_v13 | f_in_v14 | f_in_v15 | f_in_v16 | f_in_v17 | pf_in_v
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**f_in_vXX**. La frecuencia de inundaciones (corte volumen): Suma de los eventos de inundaciones para el año XX.
**pf_in_v**. Promedio de la frecuencia de inundaciones (corte volumen). Promedio de la frecuencia de inundaciones para todos los años (2007-2017).

#### Volumen promedio de encharcamientos.
Archivo de salida: **vp_en_v.csv**

La base de datos contiene los siguientes campos:

COL_ID | vp_en_v07 | vp_en_v08 | vp_en_v09 | vp_en_v10 | vp_en_v11 | vp_en_v12 | vp_en_v13 | vp_en_v14 | vp_en_v15 | vp_en_v16 | vp_en_v17 | tvp_en_v
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**vp_en_vXX**. El volumen promedio de encharcamientos (corte volumen): Promedio del volumen de los eventos de encharcamientos para el año XX.
**tvp_en_v**. Tasa promedio anual (corte volumen). Promedio del volumen promedio de encharcamientos para todos los años (2007-2017).

#### Volumen promedio de inundaciones.
Archivo de salida: **vp_in_v.csv**

La base de datos contiene los siguientes campos:

COL_ID | vp_in_v07 | vp_in_v08 | vp_in_v09 | vp_in_v10 | vp_in_v11 | vp_in_v12 | vp_in_v13 | vp_in_v14 | vp_in_v15 | vp_in_v16 | vp_in_v17 | tvp_in_v
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**vp_in_vXX**. El volumen promedio de inundaciones (corte volumen): Promedio del volumen de los eventos de inundaciones para el año XX.
**tvp_in_v**. Tasa promedio anual (corte volumen). Promedio del volumen promedio de inundaciones para todos los años (2007-2017).




### Corte Tirante

#### Frecuencia de encharcamientos.
Archivo de salida: **f_en_t.csv**
La base de datos contiene los siguientes campos:

COL_ID | f_en_t07 | f_en_t08 | f_en_t09 | f_en_t10 | f_en_t11 | f_en_t12 | f_en_t13 | f_en_t14 | f_en_t15 | f_en_t16 | f_en_t17 | pf_en_t
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**f_en_tXX**. La frecuencia de encharcamientos (corte tirante): Suma de los eventos de encharcamientos para el año XX.
**pf_en_t**. Promedio de la frecuencia de encharcamientos (corte tirante). Promedio de la frecuencia de encharcamientos para todos los años (2007-2017).

#### Frecuencia de inundaciones.
Archivo de salida: **f_in_t.csv**

La base de datos contiene los siguientes campos:

COL_ID | f_in_t07 | f_in_t08 | f_in_t09 | f_in_t10 | f_in_t11 | f_in_t12 | f_in_t13 | f_in_t14 | f_in_t15 | f_in_t16 | f_in_t17 | pf_in_t
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**f_in_tXX**. La frecuencia de inundaciones (corte tirante): Suma de los eventos de inundaciones para el año XX.
**pf_in_t**. Promedio de la frecuencia de inundaciones (corte tirante). Promedio de la frecuencia de inundaciones para todos los años (2007-2017).

#### Volumen promedio de encharcamientos.
Archivo de salida: **vp_en_t.csv**

La base de datos contiene los siguientes campos:

COL_ID | vp_en_t07 | vp_en_t08 | vp_en_t09 | vp_en_t10 | vp_en_t11 | vp_en_t12 | vp_en_t13 | vp_en_t14 | vp_en_t15 | vp_en_t16 | vp_en_t17 | tvp_en_t
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**vp_en_tXX**. El volumen promedio de encharcamientos (corte tirante): Promedio del volumen de los eventos de encharcamientos para el año XX.
**tvp_en_t**. Tasa promedio anual (corte tirante). Promedio del volumen promedio de encharcamientos para todos los años (2007-2017).

#### Volumen promedio de inundaciones.
Archivo de salida: **vp_in_t.csv**

La base de datos contiene los siguientes campos:

COL_ID | vp_in_t07 | vp_in_t08 | vp_in_t09 | vp_in_t10 | vp_in_t11 | vp_in_t12 | vp_in_t13 | vp_in_t14 | vp_in_t15 | vp_in_t16 | vp_in_t17 | tvp_in_t
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**COL_ID**. El identificador de colonia.
**vp_in_tXX**. El volumen promedio de inundaciones (corte tirante): Promedio del volumen de los eventos de inundaciones para el año XX.
**tvp_in_t**. Tasa promedio anual (corte tirante). Promedio del volumen promedio de inundaciones para todos los años (2007-2017).

**Comment by iaga** [comment]
Este es el issue que contiene las bases de datos @vichdzgeo, necesitamos generar las capas a nivel colonia a partir de los siguientes csv ubicados en la ruta:

\SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\ench_inun_0917\col_id_unico

Dentro de las carpetas:
- col_id_unico_tirante
- col_id_unico_volumen

**Comment by vichdzgeo** [comment]
## Unión de las bases de datos al shapefile de colonia y resampling a agebs
Ruta de trabajo: C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\asignacion_col_id

Se creo un código que automatiza todo el proceso. las única variable a cambiar es el nombre de la carpeta que contiene las bases de datos.
el código se encuentra en la ruta de trabajo y se llama:  union_colonias_agebs.py

Se procesa la carpeta col_id_unico_tirante

**Comment by vichdzgeo** [comment]
## Datos corregidos:

Los datos se encuentran en la siguiente ruta, se iran colocando conforme acabe el procesamiento:

C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\entregables\asignacion_col_id

**Comment by iaga** [comment]
# Generación de los mapas a partir de los datos procesados

Insumos:
C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\entregables\asignacion_col_id

A partir de los datos procesados (capas por ageb para los distintos cortes, se generaron los mapas para las capas correspondientes. Los mapas se encuentran ubicados en la ruta:

C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\asignacion_col_id\mapas

La plantilla para generar los mapas:

C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\asignacion_col_id\mapas

## Mapas de frecuencia de encharcamientos (corte tirante)
Responsable: @iaga 

## Mapas de frecuencia de encharcamientos (corte volumen)
Responsable: @aleestrada 

## Mapas de frecuencia de inundaciones (corte tirante)
Responsable: @AlfMedina 

## Mapas de frecuencia de inundaciones (corte volumen)
Responsable: @JosueMA 

## Mapas de volumen promedio (corte tirante)
Responsable: @iaga 

## Mapas de volumen promedio (corte volumen)
Responsable: @aleestrada 

## Mapas de volumen promedio (corte tirante)
Responsable: @AlfMedina 

## Mapas de volumen promedio (corte volumen)
Responsable: @JosueMA

**Comment by iaga** [comment]
![agebs_f_en_prom](https://user-images.githubusercontent.com/41757755/49317763-637d0700-f4bb-11e8-8c92-58fa3ca68edf.png)
