### ISSUE TITLE
Ajustar la regresión en R para el modelo de encharcamientos/inundaciones_v2

### ISSUE THREAD

**Issue by iaga** [sostenibilidad-unam/SHV#83]
A partir de los nuevos datos generados:

- Frecuencia de encharcamientos/inundaciones (issue #78)
- Precipitación por volumen (issue #69)
- Escorrentía
- Centralidad de la red (issue #62)

Se generarán los nuevos modelos para encharcamientos:
- Panel. Responsables: @aleestrada y @iaga 
- Regresiones. Responsables: @JosueMA y @AlfMedina 

Insumos:
Se encuentran ubicados en la carpeta: C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\modelo_ench_inund\insumos

- Frecuencia de encharcamientos/inundaciones (\frecuencia_ench_inund\agebs_f_en_t.shp, \frecuencia_ench_inund\agebs_f_in_t.shp)
- Precipitación por volumen (\vol_prec\ageb_vol_prec_utm.shp)
- Escorrentía (escorrentia\agebs_escorentia_ja_v3)
- Centralidad de la red (centralidad_lluvias\agebs_centralidad)
- Capacidad de desalojo red de lluvias (capacidad_lluvias\agebs_capacidad)

**Comment by iaga** [comment]
# Modelo de panel
## Descripción del modelo de panel

### Modelo Pool

### Efectos fijos

### Efectos aleatorios

### Modelo de efectos en el tiempo

Link para mayor información: 

## Objetivo

Explorar el ajuste del modelo de panel para toda la Ciudad de México

## Procedimiento para el modelo de panel

Se modeló el índice de frecuencia de encharcamientos (ponderado por el área) mediante el uso de modelos de panel. Los modelos se realizaron considerando los datos de las variables sin transformaciones.

A continuación se describe el procedimiento realizado:

1. Se realizó una exploración de los datos, para observar si existe heterogeneidad en el tiempo y entre AGEBS.

2. Se calculó el modelo de panel con efectos fijos. Cabe destacar que dada la estructura del modelo de efectos fijos el modelo elimina todas aquellas variables que permanezcan constantes en el tiempo. 

3. Se estima un modelo pool, el cual es un modelo de MCO que no considera la heterogenidad entre sectores ni en el tiempo.

4. Se compara el modelo pool vs el modelo de panel con efectos fijos. La hipótesis nula Ho, es que el modelo pool es mejor que el modelo de panel con efectos fijos. 

5. Se estima el modelo de panel con efectos aleatorios.

6. Una vez que se elige el tipo de modelo a utilizar. Se realizan pruebas al modelo: 
    1. Prueba de efectos aleatorios en el tiempo.
    2. Correlación serial; mediante la prueba de Breusch-Godfrey/Wooldridge para correlación serial en modelos de panel.
    3. Estacionariedad. Se aplica la prueba de  Dickey-Fuller. La hipótesis nula, es que las series tienen raíz unitaria, es decir, son no estacionarias (es estacional).
    4. Heteroscedasticidad. Se aplica el test de homoscedasticidad de Breusch-Pagan. La hipótesis nula es que existe homoscedasticidad.
    5. De ser necesario, se estiman los nuevos coeficientes usando la matriz de covarianzas robusta

### Modelo generado

#### Prueba 1.

Se realizaron las pruebas generales para el modelo (fijos/pool/aleatorios, ver descripción en la parte de arriba del issue). Los resultados de dichas pruebas se encuentran:

- Encharcamientos: ench_clusters_v.Rmd
- Inundaciones: inund_clusters_v.Rmd

Después de estudiar el comportamiento de la red de drenaje de SACMEX, se decidió incluir en el modelo el número de rejillas y bombas por AGEB. En este sentido se corrió un nuevo modelo en el que se incluyen estás nuevas variables.

Los datos de rejillas contienen el número de rejillas pluviales, de boca de tormenta y tipo Irving (issue #79). También se incluyeron las alcantarillas en el modelo con el objetivo de incluir el drenaje primario. Los resultados de dichas pruebas se encuentran:

 - Encharcamientos: ench_clusters_v_a.Rmd
 - Inundaciones: inund_clusters_v_a.Rmd

Dado que el modelo de panel con efectos fijos generaba R^2 con valores negativos, se decidió trabajar con el modelo pool. 


Ruta: \CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\panel\clusters

## Modelo final

#### Encharcamientos
Generado por: @aleestrada 

Se generó el markdown que contiene el resultado del modelo pool en el tiempo.
Ruta: \CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\panel\clusters\ench_clusters_lm.Rmd

#### Inundaciones
Generado por: @iaga 

Se generó el markdown que contiene el resultado del modelo pool en el tiempo.
Ruta: \CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\panel\clusters\inund_clusters_lm.Rmd

**Comment by iaga** [comment]
# Modelo frecuentista

Responsables: @JosueMA y @AlfMedina 

# Encharcamientos

# Inundaciones

**Comment by iaga** [comment]
# Exploración de los datos

## Descripción:

Se utilizó la base de datos `bd_ench_inunda_aj.csv`, ubicada en la ruta: 

C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\modelo_ench_inund\frecuentista

Esta base de datos se generó con el script `modelo_frec.Rmd`, que se encuentra en la ruta:

C:\Dropbox (LANCIS)\SIG\desarrollo\sig_megadapt\procesamiento\modelo_ench_inund\frecuentista

Se generaron histogramas exploratorios para cada variable y diagramas de dispersión de cada variable con respecto a la frecuencia de encharcamientos (`f_en`) e inundaciones (`f_in`). Para la frecuencia de encharcamientos (`f_en`), la frecuencia de inundaciones (`f_in`), la precipitación por volumen (`f_prec_v`), la precipitación por tirante (`f_prec_t`) y la escorrentía (`f_esc`) los histogramas exploratorios se generaron por año.

![plot_0](https://user-images.githubusercontent.com/22686851/50013536-fff8dc00-ff86-11e8-98c8-28a076dff222.png)

**Nota:** Para las variables `f_in`, `f_prec_v`, `f_prec_t` los años comprendidos son del 2007 al 2017, mientras que para la variable `f_esc` son del 2007 al 2013.

Los diagramas de dispersión se presentan de dos formas:

1. Utilizando el paquete `plotly` se generó un diagrama por comparación (frecuencia de encharcamientos o inundación vs el resto de variables) coloreando los datos por año: 

![plot_1](https://user-images.githubusercontent.com/22686851/50013552-0edf8e80-ff87-11e8-8e43-a54d197fb45b.png)

1. 1 El paquete genera gráficos interactivos, de modo que se puede utilizar el cursor colocándolo sobre un punto para desplegar información del mismo. Los datos en cada punto son: 

    i. La variable respuesta (`f_en` u `f_in`)
    ii. La variable de comparación (`f_prec_v`, `f_prec_t`, `f_esc`, `n_tramos`, `q100`, `bombeo_tot`, `rejillas`)
    iii. La ageb que representa el punto (`ageb_id`)
    iv. El año del dato (`anio`)

![plot_2](https://user-images.githubusercontent.com/22686851/50013571-1868f680-ff87-11e8-8ddd-a33305eddd0c.png)

1. 2 También pueden desplegarse los datos correspondientes a un solo año seleccionándolo en la leyenda con un doble click, o sombreando los datos que no se desean ver:

![plot_3](https://user-images.githubusercontent.com/22686851/50013586-2880d600-ff87-11e8-9b1a-efc2b1dcad90.png)

2. Al igual que los histogramas, se despliegan las comparaciones por los años comprendidos por las variables involucradas:

![plot_4](https://user-images.githubusercontent.com/22686851/50013593-3171a780-ff87-11e8-8d99-89e07e0f2311.png)

  **Nota:** Los datos se muestran en su propia escala. 

La exploración se dividió en dos archivos `Rmd`, uno para encharcamientos (`exploracion_en.Rmd`) y otro para inundaciones(`exploracion_in.Rmd`). Ambos archivos se encuntran en la ruta: 

\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund

@AlfMedina

**Comment by iaga** [comment]
# Anexos

## Clusters para el caso de escorrentía

Para el caso del modelo de clusters se consideraron los clusters defiidos por criterio de experto, ya que estos fueron los que presentaron mejor ajuste en el modelo anterior #34.

Para realizar el modelo es necesario definir el grupo de agebs que no son afectados por la escorrentía. Por lo tanto, se revisó la capa de escorrentía:(\SIG\desarrollo\sig_megadapt\procesamiento\encharcamientos_escorrentias\agebs_escorrentia_ja_v2.shp) y se comparó con la capa de clusters que se encuentra en: 

\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos\regiones_agebs\salida\agebs_cuencas_cdmx_v2.shp

Con la que se definieron los siguientes grupos:

Año|Con escorrentía|Sin escorrentía
---|---|---
2007|1,2,3,4,5,7|6,7,8
2008|1,2,3,4,5,7|6,7,8
2009|1,2,3,4,5,7|6,7,8
2010|1,2,3,4,5,7|6,7,8
2011|1,2,3,4,5,7|6,7,8
2012|1,2,3,4,5,7|6,7,8
2013|1,2,3,4,5,7|6,7,8

## Procesamiento de los datos en formato de panel

Para realizar el modelo de panel es necesario llevar los datos al formato adecuado para R. Para tal efecto se utilizó el script: \CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos\buid_dataframe_v4_iaga.py, el cual toma como insumos los nuevos datos generados.

Los campos modificados en el script:

Variable|Campo original|Nuevo campo
--|--|--
Escorrentía|esc2007| esc2007m3
Centralidad|--|n_tramos
Capacidad|Q100|q100

El archivo generado:
\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos\agebs_dat.csv

contiene los siguientes campos para el periodo con el que se cuenta con escorrentía (2007-2013):

ageb_id | ja_id | year | region | f_inunda | f_charcos | preci_v | preci | capacidad | escorren | rejillas | bombeo | centra
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by aleestrada** [comment]
Como resultado de la reunión con Luis el día de hoy se acordó que se utilizaría el modelo del árbol de regresión.

@serranoycandela y @abaezacastro la carpeta con toda la información del modelo tiene la siguiente liga:

\CARPETAS_TRABAJO\aestrada\megadaptprocesamiento\modelo_ench_inund

## El modelo: 
### Encharcamientos
\SIG\desarrollo\sig_megadapt\procesamiento\modelo_ench_inund\arbol de regresion\GBM_encharcamientos
### Inundaciones
\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\arbol de regresion\GBM_encharcamientos

## Los insumos:

\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos

**Comment by JosueMA** [comment]
# Modelo de árbol de regresión
## Insumos (se explican con más detalle en https://github.com/sostenibilidad-unam/SHV/issues/83#issuecomment-446327688).

Registros de las variables`f_en`, `f_in`, `f_prec_v`, `f_esc`, `n_tramos`, `q100`, `bombeo_tot`, `rejillas` de los años 2007 al 2013, guardados en un `.csv` en la ruta 

\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos

Esta base de datos se generó con el script `modelo_frec.Rmd`, que se encuentra en la siguiente ruta:

\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos

## Objetivo

Explorar la capacidad *predictiva* de árboles de regresión (utilizando el algoritmo de Gradient Boosting Machine) para hacer predicciones de frecuencia de encharcamientos e inundaciones para toda la Ciudad de México, con base en las variables: 

* Variables respuesta: `f_en` y `f_in`.
* Variables predictoras: `f_prec_v`, `f_esc`, `n_tramos`, `q100`, `bombeo_tot`, `rejillas`.

## Descripción del modelo

Para una explicación detallada de cómo funciona este algoritmo, ver el capítulo 8 de [*An Introduction to Statistical Learning with Applications in R*](https://www-bcf.usc.edu/~gareth/ISL/ISLR%20Seventh%20Printing.pdf) o la explicación el siguiente blog: http://uc-r.github.io/gbm_regression.

## Procedimiento

Para modelar tanto la frecuencia de encharcamientos como la de inundaciones, se implementó el siguiente procedimiento (usando R): 

1. Se partió la muestra en 2 partes: el 80% para entrenar el modelo (`datos_train`) con las variables predictoras y se guardaron las AGEBs correspondientes en otro objeto (`agebs_train`) y el 20% para probar la capacidad productiva del modelo  (`datos_test`), con sus respectivas AGEBs en otro objeto (`agebs_test`).
2. Se redondearon los valores en la columna `f_en` (frecuencia de encharcamientos) y `f_in` (frecuencia de inundaciones), ya que se buscaba modelar conteos Poisson (lo cual implica enteros positivos).
3. Para elegir los hiper-parámetros del algoritmo (GBM), se probaron diferentes valores para cada parámetro y se eligió la combinación con el menor error de predicción (para ver los valores, ver la sección `Selección de hiper-parámetros` en el html con el output del modelo). Se utilizó el paquete ‘gbm’.
4. Con los hiper-parámetros elegidos, se ajustó el modelo para toda la ciudad y luego para cada una de las 9 regiones definidas por un experto.
5. Se evaluó y graficó el error de predicción de cada modelo en los datos de entrenamiento (`datos_train`), que es un indicador del ajuste.
6. Se evaluó y graficó el error de predicción de cada modelo en los datos de prueba (`datos_test`), que es un indicador de la capacidad predictiva del modelo en bases de datos independientes a la que se usó para ajustarlo.
7. Para seleccionar el modelo que se utilizaría para el ABM, se comparó el error de los tres modelos (Panel vs Frecuentista vs Árbol de regresión), resultando el mejor modelo el árbol de regresión.

## Resultados

Se subieron los modelos resultantes de los árboles de regresión en la ruta 

\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\arbol de regresion\GBM_encharcamientos\Modelos_region

Tanto en la carpeta de encharcamientos, como en la de inundaciones se subió un ejemplo de cómo usar cada modelo para hacer predicciones; estos archivos se llaman `ejemplo_prediccion.R`. 

@iaga @aleestrada @AlfMedina

**Comment by iaga** [comment]
# Insumos para el modelo final

Las capas con las variables finales del modelo se encuentran ubicadas en la carpeta: \CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos

 - Frecuencia de encharcamientos (\frecuencia_ench_inund\agebs_f_en_t.shp)
 - Frecuencia de inundaciones (\frecuencia_ench_inund\agebs_f_in_t.shp)
 - Precipitación por volumen (\vol_prec\ageb_vol_prec_utm.shp)
 - Escorrentía (escorrentia\agebs_escorentia_ja_v3)
 - Centralidad de la red (centralidad_lluvias\agebs_centralidad)
 - Capacidad de desalojo red de lluvias (capacidad_lluvias\agebs_capacidad)
 - Rejillas (drenaje\rejillas)
 - Bombeo (drenaje\bombeo)
 - Regiones (regiones_agebs\salida\agebs_cuencas_cdmx_v2)

El periodo de tiempo modelado: 2007 al 2013.

La base de datos que contiene los campos de todas las capas para el periodo 2007 al 2013:
\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\arbol de regresion\bd_ench_inunda_2007_2013.csv

Capa| variable
--|--
agebs_f_en_t.shp|f_en
agebs_f_in_t.shp|f_in
ageb_vol_prec_utm.shp|f_prec_v
agebs_escorentia_ja_v3.shp|f_esc
agebs_centralidad.shp|n_tramos
agebs_capacidad.shp|q100
rejillas.shp|rejillas
bombeo.shp|bombeo_tot

* **f_en**: Frecuencia de encharcamientos ponderada por el área de la AGEB (2007-2013)
* **f_in**: Frecuencia de inundaciones ponderada por el área de la AGEB (2007-2013)
* **f_prec_v**: Precipitación por volumen (2007-2013)
* **f_esc**: Escorrentía (2007-2013)
* **n_tramos**: Centralidad de la red de lluvias (Número de tramos de tubería de drenaje que llegan hacia cada ageb)
* **q100**: Capacidad de desajolo (se considera constante para el periodo de tiempo)
* **rejillas**: Número total de rejillas por ageb
* **bombeo_tot**: Número total de bombas por ageb

@aleestrada @JosueMA @abaezacastro

**Comment by iaga** [comment]
El archivo que genera la base de datos del modelo, no se encuentra en la ruta especificada:

@JosueMA 
*Esta base de datos se generó con el script modelo_frec.Rmd, que se encuentra en la siguiente ruta:*
\CARPETAS_TRABAJO\aestrada\megadapt\modelo_ench_inund\insumos
